(() => {
  'use strict';
  const KEY='rideTracker.devices.v1';
  const defaults={version:1,devices:[
    {id:'phone-motion',name:'Smartphone Bewegung',type:'phone',transport:'internal',enabled:true,channels:[{id:'motion',metric:'gForce',unit:'g',enabled:true,sampleRateHz:100}]},
    {id:'phone-gps',name:'Smartphone GPS',type:'gnss',transport:'internal',enabled:true,channels:[{id:'location',metric:'location',unit:'deg',enabled:true,sampleRateHz:1},{id:'speed',metric:'speedKmh',unit:'km/h',enabled:true,sampleRateHz:1}]},
    {id:'phone-camera',name:'Smartphone Kamera',type:'camera',transport:'internal',enabled:true,channels:[{id:'video',metric:'video',unit:'stream',enabled:true}]},
    {id:'ble-heart',name:'BLE Herzfrequenz',type:'heartRate',transport:'bluetooth-le',enabled:false,channels:[{id:'heartRate',metric:'heartRateBpm',unit:'bpm',enabled:true,sampleRateHz:1}]},
    {id:'external-imu',name:'Externe IMU',type:'imu',transport:'bluetooth-le',enabled:false,channels:[{id:'acceleration',metric:'acceleration',unit:'m/s²',enabled:true,sampleRateHz:200},{id:'gyroscope',metric:'gyroscope',unit:'rad/s',enabled:true,sampleRateHz:200}]},
    {id:'external-gnss',name:'Externer GNSS-Empfänger',type:'gnss',transport:'bluetooth-le',enabled:false,channels:[{id:'position',metric:'location',unit:'deg',enabled:true,sampleRateHz:10},{id:'speed',metric:'speedKmh',unit:'km/h',enabled:true,sampleRateHz:10}]},
    {id:'external-camera',name:'Externe Kamera',type:'camera',transport:'wifi',enabled:false,channels:[{id:'video',metric:'video',unit:'stream',enabled:true}]}
  ],metricBindings:[]};
  function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
  function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
  let registry=load();
  const style=document.createElement('style');style.textContent=`
  .rt-global-menu{position:fixed;top:max(10px,env(safe-area-inset-top));left:max(10px,env(safe-area-inset-left));z-index:1000000;border-radius:999px;width:44px;height:44px;padding:0;background:#102436;color:#fff;border:1px solid #31536b}
  #rtDeviceCenter{position:fixed;inset:0;z-index:1500000;background:#02070d;color:#f5fbff;display:none;overflow:auto;padding:calc(18px + env(safe-area-inset-top)) 14px calc(24px + env(safe-area-inset-bottom))}
  #rtDeviceCenter.open{display:block}.rt-device-head{display:flex;align-items:center;gap:10px;max-width:980px;margin:auto}.rt-device-head h2{flex:1}.rt-device-grid{max-width:980px;margin:14px auto;display:grid;gap:12px}.rt-device{background:#0b1b29;border:1px solid #29435f;border-radius:16px;padding:14px}.rt-device summary{cursor:pointer;font-weight:800}.rt-device-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;margin-top:10px}.rt-device input,.rt-device select{accent-color:#00e5ff}.rt-device button{background:#102436;color:#fff;border:1px solid #31536b;border-radius:10px;padding:9px}.rt-channel{margin-top:8px;padding:9px;background:#07131f;border-radius:10px}.rt-home-panel{position:fixed;inset:0;z-index:1499999;background:#02070df2;display:none;padding:80px 18px 30px;overflow:auto}.rt-home-panel.open{display:block}.rt-home-panel nav{max-width:520px;margin:auto;display:grid;gap:10px}.rt-home-panel button{padding:15px;text-align:left;border-radius:14px;background:#102436;color:#fff;border:1px solid #31536b;font-weight:800}`;
  document.head.appendChild(style);
  const menu=document.createElement('button');menu.className='rt-global-menu';menu.textContent='☰';menu.setAttribute('aria-label','Hauptmenü');document.body.appendChild(menu);
  const home=document.createElement('section');home.className='rt-home-panel';home.innerHTML='<nav><button data-home-close>Zur aktuellen Ansicht</button><button data-home-route="home">Startseite</button><button data-home-route="record">Neue Fahrt</button><button data-home-route="devices">Geräte & Sensoren</button><button data-home-route="hud">HUD-Konfiguration</button><button data-home-route="settings">Einstellungen</button></nav>';document.body.appendChild(home);
  const center=document.createElement('section');center.id='rtDeviceCenter';center.innerHTML='<div class="rt-device-head"><button data-device-back>← Hauptmenü</button><h2>Geräte & Sensoren</h2><button data-device-add>Gerät hinzufügen</button></div><div class="rt-device-grid"></div>';document.body.appendChild(center);
  function render(){const grid=center.querySelector('.rt-device-grid');grid.innerHTML=registry.devices.map(d=>`<details class="rt-device" data-id="${d.id}"><summary>${d.name} · ${d.transport}</summary><div class="rt-device-row"><label>Aktiv</label><input data-prop="enabled" type="checkbox" ${d.enabled?'checked':''}></div><div class="rt-device-row"><label>Name</label><input data-prop="name" value="${d.name}"></div><div class="rt-device-row"><label>Transport</label><select data-prop="transport">${['internal','bluetooth-le','bluetooth-classic','usb','wifi','network','file'].map(x=>`<option ${x===d.transport?'selected':''}>${x}</option>`).join('')}</select></div><div class="rt-device-row"><label>Automatisch verbinden</label><input data-prop="autoReconnect" type="checkbox" ${d.autoReconnect?'checked':''}></div>${d.channels.map(c=>`<div class="rt-channel"><b>${c.metric}</b><div class="rt-device-row"><label>Aktiv</label><input data-channel="${c.id}" data-cprop="enabled" type="checkbox" ${c.enabled?'checked':''}></div><div class="rt-device-row"><label>Messrate Hz</label><input data-channel="${c.id}" data-cprop="sampleRateHz" type="number" min="0" value="${c.sampleRateHz||0}"></div><button data-calibrate="${c.id}">Kalibrieren</button></div>`).join('')}</details>`).join('')}
  function openDevices(){home.classList.remove('open');center.classList.add('open');render()}
  menu.onclick=()=>home.classList.toggle('open');home.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.homeClose!==undefined){home.classList.remove('open');return}const r=b.dataset.homeRoute;if(r==='devices')openDevices();else if(r==='hud')window.RideTrackerStandaloneHudEditor?.open();else if(r==='settings')document.querySelector('[data-route="Einstellungen"],.rt-dashboard-settings')?.click();else if(r==='record')document.querySelector('[data-route="Neue Fahrt"],.rt-dashboard-record')?.click();else {document.querySelector('[data-route="Start"],.rt-dashboard-home')?.click();home.classList.remove('open')}};
  center.querySelector('[data-device-back]').onclick=()=>{center.classList.remove('open');home.classList.add('open')};
  center.querySelector('[data-device-add]').onclick=()=>{const id=`custom-${Date.now()}`;registry.devices.push({id,name:'Neues Gerät',type:'custom',transport:'bluetooth-le',enabled:false,channels:[{id:'value',metric:'customValue',unit:'',enabled:true,sampleRateHz:1}]});save(registry);render()};
  center.addEventListener('input',e=>{const card=e.target.closest('[data-id]');if(!card)return;const d=registry.devices.find(x=>x.id===card.dataset.id);if(e.target.dataset.prop){d[e.target.dataset.prop]=e.target.type==='checkbox'?e.target.checked:e.target.value}else if(e.target.dataset.channel){const c=d.channels.find(x=>x.id===e.target.dataset.channel);c[e.target.dataset.cprop]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value)}save(registry)});
  center.addEventListener('click',e=>{const b=e.target.closest('[data-calibrate]');if(!b)return;const card=b.closest('[data-id]'),d=registry.devices.find(x=>x.id===card.dataset.id),c=d.channels.find(x=>x.id===b.dataset.calibrate);c.calibration={updatedAt:new Date().toISOString(),status:'ready'};save(registry);b.textContent='Kalibriert ✓'});
  window.RideTrackerDeviceCenter={open:openDevices,registry:()=>registry};
})();
