(()=>{'use strict';
const R={route:[],rides:[],map:null,track:null,markers:[],osmRides:[],selectedRide:null,place:null};
const css=`.u7{margin-top:10px;border:1px solid #29435f;background:linear-gradient(180deg,#11233a,#0c192a);border-radius:16px;padding:12px}.u7 h2{margin:0;font-size:18px}.u7-grid{display:grid;gap:10px;margin-top:10px}.u7-card{background:#081321;border-radius:12px;padding:10px}.u7-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.u7-map{height:420px;border-radius:12px;overflow:hidden;background:#06101c}.u7-list{display:grid;gap:7px;max-height:420px;overflow:auto}.u7-ride{border:1px solid #29435f;border-radius:10px;padding:9px;background:#06101c}.u7-ride b{display:block}.u7-small{font-size:12px;color:#96aac1;line-height:1.4}.u7-row{display:grid;grid-template-columns:1fr;gap:7px}.u7 input,.u7 select{width:100%;border:1px solid #29435f;border-radius:10px;padding:10px;background:#14263d;color:#f3f7fc}@media(min-width:800px){.u7-grid{grid-template-columns:2fr 1fr}.u7-row{grid-template-columns:1fr 1fr}}`;
const s=document.createElement('style');s.textContent=css;document.head.append(s);
function e(t,c,h){const n=document.createElement(t);if(c)n.className=c;if(h!==undefined)n.innerHTML=h;return n}
function hav(a,b){const r=Math.PI/180,R=6371000,q=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lon-a.lon)*r/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function dist(route){let d=0;for(let i=1;i<route.length;i++){const x=hav(route[i-1],route[i]);if(x<100)d+=x}return d}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function capture(p){const c=p.coords,q={t:Date.now(),lat:c.latitude,lon:c.longitude,alt:Number.isFinite(c.altitude)?c.altitude:null,accuracy:c.accuracy,speed:c.speed,heading:c.heading};const last=R.route.at(-1);if(!last||hav(last,q)>.4||q.t-last.t>1500)R.route.push(q);if(R.route.length>6000)R.route.shift();drawCurrent()}
const ow=navigator.geolocation?.watchPosition?.bind(navigator.geolocation),og=navigator.geolocation?.getCurrentPosition?.bind(navigator.geolocation);if(ow)navigator.geolocation.watchPosition=(ok,er,o)=>ow(p=>{capture(p);ok?.(p)},er,o);if(og)navigator.geolocation.getCurrentPosition=(ok,er,o)=>og(p=>{capture(p);ok?.(p)},er,o);
async function leaflet(){if(window.L)return;await new Promise((res,rej)=>{const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.append(l);const j=document.createElement('script');j.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';j.onload=res;j.onerror=rej;document.head.append(j)})}
function build(){const m=document.querySelector('main');if(!m||document.getElementById('u7'))return;const p=e('section','u7');p.id='u7';p.innerHTML=`<h2>Parkkarte & Fahrtenbibliothek</h2><div class="u7-small">OpenStreetMap-Karte mit aufgezeichneten Fahrten. Die GPS-Spur zeigt die horizontale Lage; die native iOS-Version ergänzt später barometrische Höhe.</div><div class="u7-row"><label><span class="label">Bahnname</span><input id="u7Name" placeholder="z. B. Voltron Nevera"></label><label><span class="label">Darstellung</span><select id="u7Color"><option value="height">Höhe</option><option value="speed">Geschwindigkeit</option><option value="plain">Einfarbig</option></select></label></div><div class="u7-actions"><button id="u7LoadRides">OSM-Bahnen laden</button><button id="u7Assign">Nächste Bahn übernehmen</button><button id="u7SaveRide">Fahrt speichern</button><button id="u7GPX">GPX exportieren</button><button id="u7Clear">Aktuelle Spur löschen</button></div><div class="u7-grid"><div class="u7-card"><div id="u7Map" class="u7-map"></div><div class="u7-small">Kartendaten © OpenStreetMap-Mitwirkende</div></div><div class="u7-card"><div class="label">Gespeicherte Fahrten</div><div id="u7List" class="u7-list"></div></div></div>`;m.append(p);bind();leaflet().then(initMap).catch(()=>document.getElementById('u7Map').textContent='Karte konnte nicht geladen werden.');loadLibrary()}
function bind(){document.getElementById('u7LoadRides').onclick=loadOSMRides;document.getElementById('u7Assign').onclick=assignNearest;document.getElementById('u7SaveRide').onclick=saveRide;document.getElementById('u7GPX').onclick=exportGPX;document.getElementById('u7Clear').onclick=()=>{R.route=[];drawCurrent()};document.getElementById('u7Color').onchange=drawCurrent;document.getElementById('stop')?.addEventListener('click',()=>setTimeout(()=>{drawCurrent();suggestNearest()},800))}
function initMap(){R.map=L.map('u7Map',{zoomControl:true}).setView([51,10],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap-Mitwirkende'}).addTo(R.map);drawCurrent()}
function drawCurrent(){if(!R.map||!R.route.length)return;if(R.track)R.map.removeLayer(R.track);const mode=document.getElementById('u7Color')?.value||'height',alts=R.route.map(x=>x.alt).filter(Number.isFinite),amin=alts.length?Math.min(...alts):0,amax=alts.length?Math.max(...alts):1,smax=Math.max(1,...R.route.map(x=>(x.speed||0)*3.6));const group=L.layerGroup();for(let i=1;i<R.route.length;i++){const p=R.route[i],q=R.route[i-1];let color='#54c7ff';if(mode==='height'&&Number.isFinite(p.alt)){const v=(p.alt-amin)/(amax-amin||1);color=`hsl(${210-v*170} 85% 55%)`}else if(mode==='speed'){const v=((p.speed||0)*3.6)/smax;color=`hsl(${210-v*210} 85% 55%)`}L.polyline([[q.lat,q.lon],[p.lat,p.lon]],{color,weight:5,opacity:.9}).addTo(group)}R.track=group.addTo(R.map);const b=L.latLngBounds(R.route.map(x=>[x.lat,x.lon]));if(b.isValid())R.map.fitBounds(b.pad(.2))}
async function loadOSMRides(){if(!R.route.length)return alert('Noch keine GPS-Position vorhanden.');const p=R.route[Math.floor(R.route.length/2)],btn=document.getElementById('u7LoadRides');btn.disabled=true;btn.textContent='Lade …';try{const q=`[out:json][timeout:20];(nwr["roller_coaster"](around:2500,${p.lat},${p.lon});nwr["attraction"="roller_coaster"](around:2500,${p.lat},${p.lon});nwr["name"]["tourism"="attraction"](around:1200,${p.lat},${p.lon}););out center tags;`,r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q,headers:{'Content-Type':'text/plain'}});if(!r.ok)throw Error('Overpass '+r.status);const j=await r.json();R.osmRides=j.elements.map(x=>({id:x.type+'/'+x.id,name:x.tags?.name||x.tags?.['name:de']||'Unbenannte Attraktion',lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon,tags:x.tags||{}})).filter(x=>Number.isFinite(x.lat));renderOSMRides()}catch(x){alert('OSM-Bahnen konnten nicht geladen werden: '+x.message)}finally{btn.disabled=false;btn.textContent='OSM-Bahnen laden'}}
function renderOSMRides(){R.markers.forEach(x=>R.map.removeLayer(x));R.markers=[];R.osmRides.forEach(x=>{const m=L.marker([x.lat,x.lon]).addTo(R.map).bindPopup(`<b>${esc(x.name)}</b><br>${esc(x.tags.operator||'')}`);m.on('click',()=>{R.selectedRide=x;document.getElementById('u7Name').value=x.name});R.markers.push(m)});suggestNearest()}
function nearestRide(){if(!R.route.length||!R.osmRides.length)return null;const p=R.route[Math.floor(R.route.length/2)];return R.osmRides.map(x=>({...x,distance:hav(p,x)})).sort((a,b)=>a.distance-b.distance)[0]}
function suggestNearest(){const n=nearestRide();if(n&&n.distance<500){R.selectedRide=n;document.getElementById('u7Name').placeholder=`Vorschlag: ${n.name} (${Math.round(n.distance)} m)`}}
function assignNearest(){const n=nearestRide();if(!n)return alert('Zuerst OSM-Bahnen laden.');R.selectedRide=n;document.getElementById('u7Name').value=n.name}
function library(){try{return JSON.parse(localStorage.getItem('ridetracker-library')||'[]')}catch{return[]}}
function saveRide(){if(R.route.length<2)return alert('Keine Fahrtstrecke vorhanden.');const rides=library(),name=document.getElementById('u7Name').value.trim()||R.selectedRide?.name||'Unbekannte Bahn',alts=R.route.map(x=>x.alt).filter(Number.isFinite);const item={id:crypto.randomUUID?.()||String(Date.now()),savedAt:new Date().toISOString(),name,osmRide:R.selectedRide,park:window.RideTrackerPlace||null,distanceM:dist(R.route),heightSpanM:alts.length?Math.max(...alts)-Math.min(...alts):null,route:R.route};rides.unshift(item);localStorage.setItem('ridetracker-library',JSON.stringify(rides.slice(0,30)));renderLibrary(rides)}
function loadLibrary(){renderLibrary(library())}
function renderLibrary(rides){const l=document.getElementById('u7List');if(!l)return;l.innerHTML=rides.length?'':'<div class="u7-small">Noch keine Fahrten gespeichert.</div>';rides.forEach(r=>{const n=e('div','u7-ride',`<b>${esc(r.name)}</b><div class="u7-small">${new Date(r.savedAt).toLocaleString()} · ${Math.round(r.distanceM)} m${Number.isFinite(r.heightSpanM)?' · '+r.heightSpanM.toFixed(1)+' m Höhe':''}</div><div class="u7-actions"><button data-show="${r.id}">Karte</button><button data-gpx="${r.id}">GPX</button><button data-del="${r.id}">Löschen</button></div>`);l.append(n)});l.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>showRide(rides.find(x=>x.id===b.dataset.show)));l.querySelectorAll('[data-gpx]').forEach(b=>exportGPX.bind(null,rides.find(x=>x.id===b.dataset.gpx)));l.querySelectorAll('[data-gpx]').forEach(b=>b.onclick=()=>exportGPX(rides.find(x=>x.id===b.dataset.gpx)));l.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const q=rides.filter(x=>x.id!==b.dataset.del);localStorage.setItem('ridetracker-library',JSON.stringify(q));renderLibrary(q)})}
function showRide(r){if(!r)return;R.route=r.route;document.getElementById('u7Name').value=r.name;drawCurrent()}
function exportGPX(ride){const route=ride?.route||R.route;if(!route.length)return alert('Keine Strecke vorhanden.');const name=ride?.name||document.getElementById('u7Name').value||'RideTracker';const pts=route.map(p=>`<trkpt lat="${p.lat}" lon="${p.lon}">${Number.isFinite(p.alt)?`<ele>${p.alt}</ele>`:''}<time>${new Date(p.t).toISOString()}</time></trkpt>`).join('');const g=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="RideTracker" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${esc(name)}</name><trkseg>${pts}</trkseg></trk></gpx>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([g],{type:'application/gpx+xml'}));a.download=name.replace(/[^a-z0-9_-]+/gi,'-')+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build):build());
})();