(() => {
  'use strict';
  const KEY = 'rideTracker.devices.v1';
  const METRICS = [
    ['heartRateBpm','Puls'],['speedKmh','Geschwindigkeit'],['gForce','G-Kräfte'],
    ['location','Position'],['altitude','Höhe'],['video','Kamera'],['vibration','Vibration']
  ];
  const DEFAULT_BINDINGS = [
    {metric:'heartRateBpm',primarySource:'ble-heart/heartRate',fallbackSources:[],minimumQuality:0.7,maxAgeMs:3000,interpolation:'hold',widgetId:'pulse'},
    {metric:'speedKmh',primarySource:'external-gnss/speed',fallbackSources:['phone-gps/speed'],minimumQuality:0.65,maxAgeMs:1500,interpolation:'linear',widgetId:'speed'},
    {metric:'gForce',primarySource:'external-imu/acceleration',fallbackSources:['phone-motion/motion'],minimumQuality:0.7,maxAgeMs:250,interpolation:'hold',widgetId:'gDial'},
    {metric:'location',primarySource:'external-gnss/position',fallbackSources:['phone-gps/location'],minimumQuality:0.6,maxAgeMs:3000,interpolation:'linear'},
    {metric:'video',primarySource:'phone-camera/video',fallbackSources:['external-camera/video'],minimumQuality:0.5,maxAgeMs:1000,interpolation:'hold'}
  ];
  function read(){try{const r=JSON.parse(localStorage.getItem(KEY)||'{}');r.metricBindings=Array.isArray(r.metricBindings)&&r.metricBindings.length?r.metricBindings:structuredClone(DEFAULT_BINDINGS);return r}catch{return {version:1,devices:[],metricBindings:structuredClone(DEFAULT_BINDINGS)}}}
  function write(r){localStorage.setItem(KEY,JSON.stringify(r))}
  function sources(registry, metric){return registry.devices.flatMap(d=>d.channels.filter(c=>c.metric===metric || (metric==='gForce'&&c.metric==='acceleration')).map(c=>`${d.id}/${c.id}`))}
  const style=document.createElement('style');style.textContent=`
    #rtSourceRouting{position:fixed;inset:0;z-index:1700000;background:#02070d;color:#f5fbff;display:none;overflow:auto;padding:calc(18px + env(safe-area-inset-top)) 14px calc(24px + env(safe-area-inset-bottom))}
    #rtSourceRouting.open{display:block}.rt-source-wrap{max-width:900px;margin:auto}.rt-source-head{display:flex;gap:10px;align-items:center}.rt-source-head h2{flex:1}.rt-source-card{background:#0b1b29;border:1px solid #29435f;border-radius:16px;padding:14px;margin-top:12px}.rt-source-row{display:grid;grid-template-columns:minmax(130px,1fr) minmax(150px,2fr);gap:10px;align-items:center;margin-top:10px}.rt-source-row input,.rt-source-row select{width:100%;background:#07131f;color:#f5fbff;border:1px solid #31536b;border-radius:9px;padding:9px}.rt-source-card button,.rt-source-head button{background:#102436;color:#fff;border:1px solid #31536b;border-radius:10px;padding:9px 12px}.rt-ble-status{font-size:.9rem;color:#9fb6c6}`;
  document.head.appendChild(style);
  const view=document.createElement('section');view.id='rtSourceRouting';view.innerHTML='<div class="rt-source-wrap"><div class="rt-source-head"><button data-source-back>← Geräte</button><h2>Quellen & Prioritäten</h2><button data-ble-connect>BLE-Pulssensor verbinden</button></div><p class="rt-ble-status" data-ble-status>Bluetoothstatus: nicht verbunden</p><div data-source-list></div></div>';document.body.appendChild(view);
  function render(){const registry=read();const list=view.querySelector('[data-source-list]');list.innerHTML=METRICS.map(([metric,label])=>{let b=registry.metricBindings.find(x=>x.metric===metric);if(!b){b={metric,primarySource:'',fallbackSources:[],minimumQuality:.6,maxAgeMs:1000,interpolation:'hold'};registry.metricBindings.push(b)}const options=sources(registry,metric);const opts=['',...options].map(s=>`<option value="${s}" ${s===b.primarySource?'selected':''}>${s||'Keine Quelle'}</option>`).join('');return `<article class="rt-source-card" data-metric="${metric}"><h3>${label}</h3><div class="rt-source-row"><label>Primärquelle</label><select data-binding="primarySource">${opts}</select></div><div class="rt-source-row"><label>Ersatzquellen</label><input data-binding="fallbackSources" value="${(b.fallbackSources||[]).join(', ')}" placeholder="Gerät/Kanal, …"></div><div class="rt-source-row"><label>Mindestqualität</label><input data-binding="minimumQuality" type="number" min="0" max="1" step="0.05" value="${b.minimumQuality??.6}"></div><div class="rt-source-row"><label>Maximales Alter</label><input data-binding="maxAgeMs" type="number" min="0" value="${b.maxAgeMs??1000}"></div><div class="rt-source-row"><label>Interpolation</label><select data-binding="interpolation">${['none','hold','linear'].map(v=>`<option ${v===(b.interpolation||'hold')?'selected':''}>${v}</option>`).join('')}</select></div></article>`}).join('');write(registry)}
  function open(){render();document.getElementById('rtDeviceCenter')?.classList.remove('open');view.classList.add('open')}
  view.querySelector('[data-source-back]').onclick=()=>{view.classList.remove('open');window.RideTrackerDeviceCenter?.open?.()};
  view.addEventListener('input',e=>{const card=e.target.closest('[data-metric]');if(!card||!e.target.dataset.binding)return;const registry=read();let b=registry.metricBindings.find(x=>x.metric===card.dataset.metric);const key=e.target.dataset.binding;let value=e.target.value;if(key==='fallbackSources')value=value.split(',').map(x=>x.trim()).filter(Boolean);if(key==='minimumQuality'||key==='maxAgeMs')value=Number(value);b[key]=value;write(registry)});
  async function connectHeartRate(){const status=view.querySelector('[data-ble-status]');if(!navigator.bluetooth){status.textContent='Web Bluetooth wird von diesem Browser nicht unterstützt. Nutze die native App.';return}try{status.textContent='Bluetoothgerät auswählen …';const device=await navigator.bluetooth.requestDevice({filters:[{services:['heart_rate']}],optionalServices:['battery_service']});const server=await device.gatt.connect();const service=await server.getPrimaryService('heart_rate');const characteristic=await service.getCharacteristic('heart_rate_measurement');await characteristic.startNotifications();characteristic.addEventListener('characteristicvaluechanged',event=>{const data=event.target.value,flags=data.getUint8(0),bpm=(flags&1)?data.getUint16(1,true):data.getUint8(1);const sample={metric:'heartRateBpm',value:bpm,unit:'bpm',source:'ble-heart/heartRate',quality:1,timestampMs:performance.now()};window.RideTrackerExternalTelemetry=window.RideTrackerExternalTelemetry||{};window.RideTrackerExternalTelemetry.heartRateBpm=sample;window.dispatchEvent(new CustomEvent('ridetracker-telemetry',{detail:sample}));status.textContent=`Verbunden: ${device.name||'BLE-Pulssensor'} · ${bpm} BPM`;});status.textContent=`Verbunden: ${device.name||'BLE-Pulssensor'}`;}catch(error){status.textContent=`Bluetoothfehler: ${error?.message||error}`}}
  view.querySelector('[data-ble-connect]').onclick=connectHeartRate;
  const attach=()=>{const head=document.querySelector('#rtDeviceCenter .rt-device-head');if(head&&!head.querySelector('[data-source-open]')){const b=document.createElement('button');b.dataset.sourceOpen='';b.textContent='Quellen & Prioritäten';b.onclick=open;head.appendChild(b)}};
  new MutationObserver(attach).observe(document.documentElement,{childList:true,subtree:true});attach();
  window.RideTrackerSourceRouting={open,resolve(metric,candidates){const registry=read(),policy=registry.metricBindings.find(x=>x.metric===metric);if(!policy)return candidates?.[0]||null;const order=[policy.primarySource,...(policy.fallbackSources||[])];const now=performance.now();return order.map(id=>candidates?.find(c=>c.source===id)).find(c=>c&&c.quality>=(policy.minimumQuality??0)&&now-c.timestampMs<=(policy.maxAgeMs??Infinity))||null}};
})();