(() => {
  'use strict';

  const gps = { active:false, startMono:0, watchId:null, points:[], last:null };
  const db = () => window.RideTrackerDatabase;
  const finite = value => Number.isFinite(Number(value));
  const elapsedSeconds = () => gps.active ? Math.max(0, (performance.now() - gps.startMono) / 1000) : 0;
  const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
  const FOCUS_KEY = 'rideTracker.libraryFocusRideId.v1';
  const COUNTRY_CODES = 'AD AE AF AG AI AL AM AO AR AT AU AZ BA BB BD BE BF BG BH BI BJ BN BO BR BS BT BW BY BZ CA CD CF CG CH CI CL CM CN CO CR CU CV CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET FI FJ FM FR GA GB GD GE GH GM GN GQ GR GT GW GY HK HN HR HT HU ID IE IL IN IQ IR IS IT JM JO JP KE KG KH KI KM KN KP KR KW KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MR MT MU MV MW MX MY MZ NA NE NG NI NL NO NP NR NZ OM PA PE PG PH PK PL PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SI SK SL SM SN SO SR SS ST SV SY SZ TD TG TH TJ TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VN VU WS YE ZA ZM ZW'.split(' ');
  const countryNames = typeof Intl.DisplayNames === 'function' ? new Intl.DisplayNames(['de'], { type:'region' }) : null;
  const countryName = code => { try { return countryNames?.of(code) || code; } catch { return code; } };

  async function cached(key, loader, ttl = CACHE_TTL_MS) {
    const database = db(); const cacheKey=`reference:${key}`;
    if(database){try{const hit=await database.get(database.stores.cache,cacheKey);if(hit&&Date.now()-Number(hit.savedAt||0)<ttl)return hit.value;}catch(_){}}
    const value=await loader();
    if(database){try{await database.put(database.stores.cache,cacheKey,{savedAt:Date.now(),value});}catch(_){}}
    return value;
  }
  async function fetchJson(url, options = {}, timeoutMs = 12000) {
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);
    try{const response=await fetch(url,{...options,signal:controller.signal,headers:{Accept:'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(`${new URL(url).hostname}: HTTP ${response.status}`);return await response.json();}finally{clearTimeout(timer);}
  }
  const radians = deg => deg*Math.PI/180;
  function distanceMeters(a,b){const R=6371000,dLat=radians(Number(b.latitude)-Number(a.latitude)),dLon=radians(Number(b.longitude)-Number(a.longitude)),lat1=radians(Number(a.latitude)),lat2=radians(Number(b.latitude));const q=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
  const normalizeName = value => String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();

  function startGpsCapture(){if(gps.active)return;gps.active=true;gps.startMono=performance.now();gps.points=[];gps.last=null;if(!navigator.geolocation)return;try{gps.watchId=navigator.geolocation.watchPosition(position=>{const c=position.coords||{};if(!finite(c.latitude)||!finite(c.longitude))return;const point={timestamp:elapsedSeconds(),latitude:Number(c.latitude),longitude:Number(c.longitude),altitude:finite(c.altitude)?Number(c.altitude):null,horizontalAccuracyM:finite(c.accuracy)?Number(c.accuracy):null,altitudeAccuracyM:finite(c.altitudeAccuracy)?Number(c.altitudeAccuracy):null,speedMS:finite(c.speed)?Math.max(0,Number(c.speed)):null,speedKmh:finite(c.speed)?Math.max(0,Number(c.speed))*3.6:null,headingDeg:finite(c.heading)?Number(c.heading):null,gpsTimestampMs:Number(position.timestamp)||Date.now(),source:'internal-gps'};gps.points.push(point);gps.last=point;window.dispatchEvent(new CustomEvent('ridetracker:recording-gps',{detail:point}));},error=>window.dispatchEvent(new CustomEvent('ridetracker:recording-gps-error',{detail:{code:error?.code,message:error?.message}})),{enableHighAccuracy:true,maximumAge:500,timeout:12000});}catch(error){console.warn('[RideTracker GPS]',error);}}
  function stopGpsCapture(){gps.active=false;if(gps.watchId!=null&&navigator.geolocation){try{navigator.geolocation.clearWatch(gps.watchId);}catch(_){}}gps.watchId=null;}
  function nearestGps(timestamp){const values=gps.points;if(!values.length)return null;let lo=0,hi=values.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(values[mid].timestamp<timestamp)lo=mid+1;else hi=mid;}if(lo>0&&Math.abs(values[lo-1].timestamp-timestamp)<=Math.abs(values[lo].timestamp-timestamp))lo-=1;return values[lo];}
  function mergeGpsIntoSamples(samples){if(!Array.isArray(samples)||!samples.length||!gps.points.length)return samples||[];return samples.map((sample,index)=>{const timestamp=finite(sample.timestamp)?Number(sample.timestamp):finite(sample.t)?Number(sample.t):index/50,point=nearestGps(timestamp);if(!point)return sample;return{...sample,latitude:point.latitude,longitude:point.longitude,altitude:point.altitude,horizontalAccuracyM:point.horizontalAccuracyM,altitudeAccuracyM:point.altitudeAccuracyM,speedMS:finite(sample.speedMS)?sample.speedMS:point.speedMS,speedKmh:finite(sample.speedKmh)?sample.speedKmh:point.speedKmh,headingDeg:point.headingDeg,gpsSource:point.source};});}
  async function persistGps(rideId){if(!rideId||!gps.points.length)return;const database=db();if(!database)return;const ridePackage=await database.get(database.stores.ridePackages,rideId);if(!ridePackage)return;ridePackage.document=ridePackage.document||{};ridePackage.document.samples=mergeGpsIntoSamples(Array.isArray(ridePackage.document.samples)?ridePackage.document.samples:[]);ridePackage.document.gps={...(ridePackage.document.gps||{}),points:gps.points.slice(),source:'internal-gps',capturedAt:new Date().toISOString()};ridePackage.gpsPointCount=gps.points.length;await database.put(database.stores.ridePackages,rideId,ridePackage);window.dispatchEvent(new CustomEvent('ridetracker:gps-persisted',{detail:{rideId,count:gps.points.length}}));}

  const osmProvider={id:'osm',name:'OpenStreetMap',priority:20,async nearbyParks(point,radiusM=8000){const query=`[out:json][timeout:12];(nwr(around:${radiusM},${point.latitude},${point.longitude})["tourism"="theme_park"];nwr(around:${radiusM},${point.latitude},${point.longitude})["leisure"="amusement_park"];);out center tags;`;const data=await fetchJson(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`);return(data.elements||[]).map(element=>({provider:'osm',id:`${element.type}/${element.id}`,name:element.tags?.name||'Unbenannter Park',latitude:Number(element.center?.lat??element.lat),longitude:Number(element.center?.lon??element.lon),tags:element.tags||{},raw:element})).filter(x=>finite(x.latitude)&&finite(x.longitude));},async parkAttractions(park,radiusM=3500){const query=`[out:json][timeout:12];(nwr(around:${radiusM},${park.latitude},${park.longitude})["roller_coaster"];nwr(around:${radiusM},${park.latitude},${park.longitude})["attraction"="roller_coaster"];nwr(around:${radiusM},${park.latitude},${park.longitude})["tourism"="attraction"];);out center tags;`;const data=await fetchJson(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`);return(data.elements||[]).map(element=>({provider:'osm',id:`${element.type}/${element.id}`,name:element.tags?.name||'Unbenannte Attraktion',latitude:Number(element.center?.lat??element.lat),longitude:Number(element.center?.lon??element.lon),tags:element.tags||{},wikidata:element.tags?.wikidata||null,raw:element})).filter(x=>x.name);}};
  const themeParksWikiProvider={id:'themeparks-wiki',name:'ThemeParks.wiki',priority:30,async destinations(){const data=await cached('themeparkswiki:destinations',()=>fetchJson('https://api.themeparks.wiki/v1/destinations'),24*60*60*1000);return Array.isArray(data?.destinations)?data.destinations:[];},async allParks(){const destinations=await this.destinations();return destinations.flatMap(destination=>(destination.parks||[]).map(park=>({provider:'themeparks-wiki',id:park.id,name:park.name,destinationId:destination.id,destinationName:destination.name})));},async parkAttractions(parkId){if(!parkId)return[];const data=await cached(`themeparkswiki:children:${parkId}`,()=>fetchJson(`https://api.themeparks.wiki/v1/entity/${encodeURIComponent(parkId)}/children`),6*60*60*1000);const children=Array.isArray(data?.children)?data.children:Array.isArray(data)?data:[];return children.filter(child=>String(child.entityType||child.type||'').toUpperCase()==='ATTRACTION').map(child=>({provider:'themeparks-wiki',id:child.id,name:child.name,latitude:Number(child.location?.latitude),longitude:Number(child.location?.longitude),entityType:child.entityType,raw:child}));}};
  const wikidataProvider={id:'wikidata',name:'Wikidata',priority:25,async entity(qid){if(!/^Q\d+$/.test(String(qid||'')))return null;const data=await cached(`wikidata:${qid}`,()=>fetchJson(`https://www.wikidata.org/wiki/Special:EntityData/${encodeURIComponent(qid)}.json`),30*24*60*60*1000);return data?.entities?.[qid]||null;},async technicalReference(qid){const entity=await this.entity(qid);if(!entity)return null;const amount=property=>{const raw=entity.claims?.[property]?.[0]?.mainsnak?.datavalue?.value;return raw&&raw.amount!=null?Number(raw.amount):null;};return{provider:'wikidata',id:qid,name:entity.labels?.de?.value||entity.labels?.en?.value||qid,lengthM:amount('P2043'),heightM:amount('P2048'),maxSpeed:amount('P2052'),inception:entity.claims?.P571?.[0]?.mainsnak?.datavalue?.value?.time||null,raw:entity};}};

  async function reverseCountry(point){const lat=Number(point?.latitude),lon=Number(point?.longitude);if(!finite(lat)||!finite(lon))return null;const key=`country:${lat.toFixed(2)}:${lon.toFixed(2)}`;return cached(key,async()=>{const data=await fetchJson(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=3&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,{},10000);const code=String(data?.address?.country_code||'').toUpperCase();return code?{code,name:data?.address?.country||countryName(code)}:null;},30*24*60*60*1000);}
  function normalizeOsmElement(element){const tags=element.tags||{},latitude=Number(element.center?.lat??element.lat),longitude=Number(element.center?.lon??element.lon);return{provider:'osm',id:`${element.type}/${element.id}`,name:tags.name||'Unbenannt',latitude,longitude,tags,wikidata:tags.wikidata||null,raw:element};}
  async function downloadCountryPack(code,force=false){code=String(code||'').toUpperCase();if(!COUNTRY_CODES.includes(code))throw new Error('Ungültiges Land.');const database=db(),cacheKey=`reference:country-pack:${code}`;if(!force&&database){try{const hit=await database.get(database.stores.cache,cacheKey);if(hit?.value)return hit.value;}catch(_){}}
    const query=`[out:json][timeout:35];area["ISO3166-1"="${code}"][boundary="administrative"]->.country;(nwr(area.country)["tourism"="theme_park"];nwr(area.country)["leisure"="amusement_park"];nwr(area.country)["roller_coaster"];nwr(area.country)["attraction"="roller_coaster"];);out center tags;`;
    const data=await fetchJson(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`,{},45000);const all=(data.elements||[]).map(normalizeOsmElement).filter(x=>x.name&&finite(x.latitude)&&finite(x.longitude));const parks=all.filter(x=>x.tags?.tourism==='theme_park'||x.tags?.leisure==='amusement_park'),attractions=all.filter(x=>x.tags?.roller_coaster!=null||x.tags?.attraction==='roller_coaster');const pack={version:1,countryCode:code,countryName:countryName(code),downloadedAt:new Date().toISOString(),parks,attractions};if(database)await database.put(database.stores.cache,cacheKey,{savedAt:Date.now(),value:pack});return pack;}
  async function countryPack(code){const database=db();if(!database)return null;try{return(await database.get(database.stores.cache,`reference:country-pack:${String(code||'').toUpperCase()}`))?.value||null;}catch{return null;}}
  async function parksForCountry(code){const pack=await countryPack(code);if(pack?.parks?.length)return pack.parks;return (await downloadCountryPack(code)).parks;}
  async function communityMatch(park){const directory=await themeParksWikiProvider.allParks();const needle=normalizeName(park?.name);if(!needle)return null;let best=null,bestScore=0;for(const item of directory){const candidate=normalizeName(item.name),score=candidate===needle?1:(candidate.includes(needle)||needle.includes(candidate)?0.85:0);if(score>bestScore){bestScore=score;best=item;}}return bestScore>=0.8?{...best,nameScore:bestScore}:null;}
  async function attractionsForPark(park,countryCode){const pack=countryCode?await countryPack(countryCode):null;let osm=[];if(pack?.attractions?.length&&finite(park.latitude)&&finite(park.longitude))osm=pack.attractions.filter(a=>distanceMeters(park,a)<5000);else if(finite(park.latitude)&&finite(park.longitude)){try{osm=await osmProvider.parkAttractions(park);}catch(_){}}
    let community=[];try{const match=await communityMatch(park);if(match)community=await themeParksWikiProvider.parkAttractions(match.id);}catch(_){}
    const merged=new Map();for(const item of [...community,...osm]){const key=normalizeName(item.name);if(!key)continue;if(!merged.has(key))merged.set(key,item);else merged.set(key,{...merged.get(key),...item,providers:[...(merged.get(key).providers||[merged.get(key).provider]),item.provider]});}return [...merged.values()].sort((a,b)=>a.name.localeCompare(b.name,'de'));}

  const providers=new Map([[osmProvider.id,osmProvider],[themeParksWikiProvider.id,themeParksWikiProvider],[wikidataProvider.id,wikidataProvider]]);
  const referenceEngine={providers,providerList:()=>[...providers.values()].map(({id,name,priority})=>({id,name,priority})),getProvider:id=>providers.get(id),nearbyParks:point=>osmProvider.nearbyParks(point),themeParkDirectory:()=>themeParksWikiProvider.allParks(),attractionsForCommunityPark:parkId=>themeParksWikiProvider.parkAttractions(parkId),wikidataReference:qid=>wikidataProvider.technicalReference(qid),reverseCountry,downloadCountryPack,countryPack,parksForCountry,attractionsForPark,communityMatch,cached};

  const style=document.createElement('style');style.id='rtReference54Style';style.textContent=`#rtReference54{margin-top:12px;border:1px solid #35536f;border-radius:16px;background:#091626;padding:14px;color:#fff}#rtReference54 h3{margin:0 0 4px}.rt54-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.rt54-grid label{display:grid;gap:5px;color:#96aac1;font-size:12px}.rt54-grid select,.rt54-grid button{width:100%}.rt54-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rt54-status{margin-top:9px;color:#96aac1;font-size:12px;line-height:1.45}@media(max-width:600px){.rt54-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  async function currentRidePackage(){const id=sessionStorage.getItem(FOCUS_KEY);if(!id||!db())return null;return db().get(db().stores.ridePackages,id);}
  function packageGps(pkg){const direct=Array.isArray(pkg?.document?.gps?.points)?pkg.document.gps.points:[];if(direct.length)return direct;const samples=Array.isArray(pkg?.document?.samples)?pkg.document.samples:[];return samples.filter(s=>finite(s.latitude)&&finite(s.longitude));}
  function countryOptions(selected=''){return `<option value="">Land auswählen …</option>${COUNTRY_CODES.map(code=>`<option value="${code}" ${code===selected?'selected':''}>${countryName(code)}</option>`).join('')}`;}
  async function installReferencePanel(){const detail=document.querySelector('#rtRideLibrary .rt-ride-detail');if(!detail||detail.querySelector('#rtReference54'))return;detail.querySelector('[data-rt53-park]')?.setAttribute('hidden','');const panel=document.createElement('section');panel.id='rtReference54';panel.innerHTML=`<h3>Park & Attraktion zuordnen</h3><div class="rt54-status">Online-Erkennung wird bevorzugt. Ohne GPS kannst du Land, Park und Attraktion manuell auswählen; ein Land lässt sich für spätere Offline-Nutzung zwischenspeichern.</div><div class="rt54-grid"><label>Land<select data-country>${countryOptions()}</select></label><label>Park<select data-park disabled><option>Park auswählen …</option></select></label><label style="grid-column:1/-1">Attraktion<select data-attraction disabled><option>Attraktion auswählen …</option></select></label></div><div class="rt54-actions"><button data-auto>GPS automatisch erkennen</button><button data-download>Land offline speichern</button></div><div class="rt54-status" data-status></div>`;detail.querySelector('.rt-detail-card')?.after(panel);
    const country=panel.querySelector('[data-country]'),park=panel.querySelector('[data-park]'),attraction=panel.querySelector('[data-attraction]'),status=panel.querySelector('[data-status]');let parks=[];
    async function loadParks(){const code=country.value;if(!code)return;status.textContent='Parks werden geladen …';try{parks=await parksForCountry(code);park.innerHTML='<option value="">Park auswählen …</option>'+parks.map((p,i)=>`<option value="${i}">${String(p.name).replace(/</g,'&lt;')}</option>`).join('');park.disabled=false;status.textContent=`${parks.length} Parks für ${countryName(code)} verfügbar.`;}catch(error){status.textContent=`Parks konnten nicht geladen werden: ${error.message}`;}}
    country.onchange=()=>void loadParks();park.onchange=async()=>{const selected=parks[Number(park.value)];if(!selected){attraction.disabled=true;return;}status.textContent='Attraktionen werden geladen …';const items=await attractionsForPark(selected,country.value);attraction.innerHTML='<option value="">Attraktion auswählen …</option>'+items.map((a,i)=>`<option value="${i}">${String(a.name).replace(/</g,'&lt;')}</option>`).join('');attraction._items=items;attraction.disabled=false;status.textContent=`${items.length} Attraktionen verfügbar.`;};
    panel.querySelector('[data-download]').onclick=async()=>{if(!country.value)return alert('Bitte zuerst ein Land auswählen.');status.textContent='Offline-Paket wird geladen …';try{const pack=await downloadCountryPack(country.value,true);status.textContent=`Offline-Paket ${pack.countryName}: ${pack.parks.length} Parks, ${pack.attractions.length} Achterbahnen/Attraktionen gespeichert.`;await loadParks();}catch(error){status.textContent=`Offline-Paket fehlgeschlagen: ${error.message}`;}};
    panel.querySelector('[data-auto]').onclick=async()=>{const pkg=await currentRidePackage(),points=packageGps(pkg);if(!points.length){status.textContent='Keine GPS-Daten vorhanden. Bitte Land, Park und Attraktion manuell wählen.';return;}status.textContent='Land und Park werden aus GPS bestimmt …';try{const center=points[Math.floor(points.length/2)],detectedCountry=await reverseCountry(center);if(detectedCountry){country.value=detectedCountry.code;await loadParks();}const nearby=await osmProvider.nearbyParks(center);if(nearby.length){const closest=[...nearby].sort((a,b)=>distanceMeters(center,a)-distanceMeters(center,b))[0];const index=parks.findIndex(p=>normalizeName(p.name)===normalizeName(closest.name));if(index>=0){park.value=String(index);park.onchange();}status.textContent=`GPS-Kandidat: ${closest.name}${detectedCountry?` · ${detectedCountry.name}`:''}.`;}else status.textContent='Kein Park eindeutig über GPS gefunden. Bitte aus der Liste auswählen.';}catch(error){status.textContent=`GPS-Erkennung fehlgeschlagen: ${error.message}. Manuelle Auswahl bleibt verfügbar.`;}};
  }
  const observer=new MutationObserver(()=>void installReferencePanel());observer.observe(document.body,{childList:true,subtree:true});void installReferencePanel();

  window.addEventListener('ridetracker:recording-started',startGpsCapture);window.addEventListener('ridetracker:recording-stopped',stopGpsCapture);window.addEventListener('ridetracker:ride-saved',event=>void persistGps(event.detail?.rideId));window.addEventListener('ridetracker:new-ride-session',()=>{gps.points=[];gps.last=null;});
  window.RideTrackerGpsCapture={start:startGpsCapture,stop:stopGpsCapture,points:()=>gps.points.slice(),last:()=>gps.last,persistGps};window.RideTrackerReferenceEngine=referenceEngine;
})();
