(() => {
  'use strict';
  const FOCUS_KEY='rideTracker.libraryFocusRideId.v1';
  const META_KEY='rideTracker.savedRides.v2';
  const db=()=>window.RideTrackerDatabase;
  const engine=()=>window.RideTrackerReferenceEngine;
  const confidence=()=>window.RideTrackerConfidenceEngine;
  const finite=value=>Number.isFinite(Number(value));
  const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  async function fetchJson(url,timeoutMs=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Coasterpedia HTTP ${response.status}`);return response.json();}finally{clearTimeout(timer);}}
  async function coasterpediaSearch(name,parkName=''){
    const query=`${name}${parkName?` ${parkName}`:''}`.trim();if(!query)return[];
    const url=`https://coasterpedia.net/w/api.php?action=query&list=search&srnamespace=0&srlimit=8&srsearch=${encodeURIComponent(query)}&format=json&origin=*`;
    const data=await fetchJson(url);return(data?.query?.search||[]).map(item=>({title:item.title,pageid:item.pageid,snippet:item.snippet}));
  }
  async function coasterpediaWikitext(title){const url=`https://coasterpedia.net/w/api.php?action=query&prop=revisions&rvprop=content&rvslots=main&titles=${encodeURIComponent(title)}&format=json&formatversion=2&origin=*`;const data=await fetchJson(url);return data?.query?.pages?.[0]?.revisions?.[0]?.slots?.main?.content||'';}
  function field(text,name){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),match=text.match(new RegExp(`\\|\\s*${escaped}\\s*=\\s*([^\\n\\r}]*)`,'i'));return match?match[1].replace(/<!--.*?-->/g,'').replace(/\[\[([^|\]]+\|)?([^\]]+)\]\]/g,'$2').replace(/<[^>]+>/g,'').trim():'';}
  function numberField(text,names){for(const name of names){const value=field(text,name),match=value.replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);if(match)return Number(match[0]);}return null;}
  function durationSeconds(value){const match=String(value||'').match(/(?:(\d+):)?(\d+)(?::(\d+))?/);if(!match)return null;if(match[3]!=null)return Number(match[1]||0)*3600+Number(match[2])*60+Number(match[3]);if(match[1]!=null)return Number(match[1])*60+Number(match[2]);return Number(match[2]);}
  async function coasterpediaReference(name,parkName=''){
    const results=await coasterpediaSearch(name,parkName);if(!results.length)return null;
    const targetName=norm(name),targetPark=norm(parkName);let best=results[0],bestScore=-1;
    for(const result of results){const n=norm(result.title);let score=n===targetName?1:n.includes(targetName)||targetName.includes(n)?.85:0;if(targetPark&&norm(result.snippet).includes(targetPark))score+=.25;if(score>bestScore){bestScore=score;best=result;}}
    const text=await coasterpediaWikitext(best.title);if(!text)return null;
    const units=field(text,'units').toLowerCase(),imperial=units.includes('imperial')||/united states|usa/i.test(field(text,'country'));
    let speed=numberField(text,['speed']),length=numberField(text,['length','track_length']),height=numberField(text,['height']),drop=numberField(text,['drop']),gForce=numberField(text,['g-force','g_force']);
    if(imperial){if(finite(speed))speed*=1.609344;if(finite(length))length*=0.3048;if(finite(height))height*=0.3048;if(finite(drop))drop*=0.3048;}
    return{provider:'coasterpedia',name:field(text,'name')||best.title,park:field(text,'park')||parkName,country:field(text,'country'),manufacturer:field(text,'manufacturer'),speedKmh:finite(speed)?speed:null,lengthM:finite(length)?length:null,heightM:finite(height)?height:null,dropM:finite(drop)?drop:null,maxG:finite(gForce)?gForce:null,durationS:durationSeconds(field(text,'duration')),inversions:numberField(text,['inversions','rider_inversions']),url:`https://coasterpedia.net/wiki/${encodeURIComponent(best.title.replace(/ /g,'_'))}`,license:'CC BY-SA',pageTitle:best.title};
  }
  async function currentPackage(){const id=sessionStorage.getItem(FOCUS_KEY);if(!id||!db())return null;return db().get(db().stores.ridePackages,id);}
  async function currentSelection(panel){const country=panel.querySelector('[data-country]')?.value,parkName=panel.querySelector('[data-park]')?.selectedOptions?.[0]?.textContent?.trim(),rideName=panel.querySelector('[data-attraction]')?.selectedOptions?.[0]?.textContent?.trim();if(!country||!parkName||!rideName||!panel.querySelector('[data-attraction]')?.value)return null;const parks=await engine()?.parksForCountry?.(country)||[],park=parks.find(p=>norm(p.name)===norm(parkName));if(!park)return null;const attractions=await engine()?.attractionsForPark?.(park,country)||[],attraction=attractions.find(a=>norm(a.name)===norm(rideName));return{country,parkName,rideName,park,attraction};}
  function diffPercent(own,ref){if(!finite(own)||!finite(ref)||Number(ref)===0)return null;return((Number(own)-Number(ref))/Number(ref))*100;}
  function metric(label,own,ref,unit,digits=1){const delta=diffPercent(own,ref);return`<div class="rt56-metric"><span>${label}</span><b>${finite(own)?Number(own).toFixed(digits):'–'} ${unit}</b><small>Referenz ${finite(ref)?Number(ref).toFixed(digits):'–'} ${unit}${delta==null?'':` · ${delta>=0?'+':''}${delta.toFixed(1)}%`}</small></div>`;}
  function localCommunity(rideName,parkName,currentId){let meta=[];try{meta=JSON.parse(localStorage.getItem(META_KEY)||'[]');if(!Array.isArray(meta))meta=[];}catch{}const same=meta.filter(r=>r.id!==currentId&&norm(r.track||r.title)===norm(rideName)&&(!parkName||norm(r.park)===norm(parkName)));return{count:same.length};}
  async function saveAssignment(selection,reference,score){const id=sessionStorage.getItem(FOCUS_KEY),database=db();if(!id||!database)return;const pkg=await database.get(database.stores.ridePackages,id);if(pkg){pkg.parkName=selection.parkName;pkg.rideName=selection.rideName;pkg.document=pkg.document||{};pkg.document.context={...(pkg.document.context||{}),parkName:selection.parkName,rideName:selection.rideName,countryCode:selection.country};pkg.document.reference={selectedAt:new Date().toISOString(),confidencePercent:score?.percent??null,providers:['OpenStreetMap','ThemeParks.wiki','Wikidata',reference?'Coasterpedia':null].filter(Boolean),coasterpedia:reference};await database.put(database.stores.ridePackages,id,pkg);}let meta=[];try{meta=JSON.parse(localStorage.getItem(META_KEY)||'[]');}catch{}if(Array.isArray(meta)){const ride=meta.find(r=>r.id===id);if(ride){ride.park=selection.parkName;ride.track=selection.rideName;ride.updatedAt=new Date().toISOString();localStorage.setItem(META_KEY,JSON.stringify(meta));}}window.dispatchEvent(new CustomEvent('ridetracker:reference-assigned',{detail:{rideId:id,park:selection.parkName,ride:selection.rideName,confidence:score?.percent??null}}));}
  function ensureHost(panel){let host=panel.querySelector('[data-comparison56]');if(!host){host=document.createElement('div');host.dataset.comparison56='';host.style.marginTop='10px';panel.appendChild(host);}return host;}
  async function renderComparison(panel){const host=ensureHost(panel),selection=await currentSelection(panel);if(!selection){host.innerHTML='';return;}host.innerHTML='<div class="rt56-card">Referenzdaten werden geladen …</div>';try{const pkg=await currentPackage();if(!pkg)throw new Error('RidePackage fehlt.');const own=confidence()?.ownMetrics?.(pkg)||{};let reference=null;try{reference=await coasterpediaReference(selection.rideName,selection.parkName);}catch(error){console.warn('[Coasterpedia]',error);}const score=await confidence()?.scoreCandidate?.({pkg,park:selection.park,attraction:selection.attraction,parkName:selection.parkName,attractionName:selection.rideName});const community=localCommunity(selection.rideName,selection.parkName,sessionStorage.getItem(FOCUS_KEY));host.innerHTML=`<div class="rt56-card"><div class="rt56-head"><div><strong>${escapeHtml(selection.rideName)}</strong><small>${escapeHtml(selection.parkName)}</small></div><b>${score?.percent??0}% Confidence</b></div><div class="rt56-grid">${metric('Max. Tempo',own.maxSpeedKmh,reference?.speedKmh,'km/h',1)}${metric('Strecke',own.distanceM,reference?.lengthM,'m',0)}${metric('Max. G',own.maxG,reference?.maxG,'g',2)}${metric('Dauer',own.durationS,reference?.durationS,'s',0)}</div><div class="rt56-note">${reference?`Community-Referenz: Coasterpedia (${escapeHtml(reference.license)}). ${reference.manufacturer?`Hersteller: ${escapeHtml(reference.manufacturer)}. `:''}`:'Für diese Auswahl wurden keine technischen Coasterpedia-Werte gefunden.'} Weitere Quellen: OpenStreetMap für Position/Geometrie, ThemeParks.wiki für Park-/Attraktionsverzeichnis und Wikidata, falls verknüpft. ${community.count?`${community.count} weitere lokale RideTracker-Fahrt${community.count===1?'':'en'} derselben Bahn vorhanden.`:'Noch keine weitere lokale Fahrt derselben Bahn.'}</div><div class="rt56-actions"><button data-save-reference>Zuordnung & Referenz speichern</button>${reference?.url?`<a href="${reference.url}" target="_blank" rel="noopener">Coasterpedia öffnen</a>`:''}</div></div>`;host.querySelector('[data-save-reference]').onclick=async()=>{await saveAssignment(selection,reference,score);host.querySelector('[data-save-reference]').textContent='Gespeichert ✓';};}catch(error){host.innerHTML=`<div class="rt56-card">Vergleich konnte nicht geladen werden: ${escapeHtml(error?.message||error)}</div>`;}}
  const style=document.createElement('style');style.textContent=`.rt56-card{border:1px solid #29435f;border-radius:13px;background:#07131f;padding:11px;color:#fff}.rt56-head{display:flex;justify-content:space-between;gap:10px;align-items:start}.rt56-head small{display:block;color:#96aac1;margin-top:3px}.rt56-head>b{color:#5fd0ff;white-space:nowrap}.rt56-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.rt56-metric{background:#0b1b29;border-radius:9px;padding:8px}.rt56-metric span,.rt56-metric small{display:block;color:#96aac1;font-size:10px}.rt56-metric b{display:block;margin:4px 0}.rt56-note{margin-top:10px;color:#96aac1;font-size:12px;line-height:1.45}.rt56-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rt56-actions a{padding:10px;border:1px solid #35536f;border-radius:10px;color:#fff;text-decoration:none}@media(max-width:540px){.rt56-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  function install(){const panel=document.querySelector('#rtReference54');if(!panel||panel.dataset.compare56)return;panel.dataset.compare56='1';ensureHost(panel);panel.addEventListener('change',event=>{if(event.target.matches('[data-park],[data-attraction]'))setTimeout(()=>void renderComparison(panel),50);});}
  const observer=new MutationObserver(install);observer.observe(document.body,{childList:true,subtree:true});install();
  window.RideTrackerCommunityReference={search:coasterpediaSearch,reference:coasterpediaReference,renderComparison};
})();
