(()=>{'use strict';
const U={route:[],motion:[],park:null,place:null,editing:false,rotX:-0.55,rotZ:-0.7,zoom:1,drag:null};
const css=`
.u6-panel{margin-top:10px;border:1px solid #29435f;background:linear-gradient(180deg,#11233a,#0c192a);border-radius:16px;padding:12px}.u6-head{display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap}.u6-head h2{font-size:17px;margin:0}.u6-actions{display:flex;gap:7px;flex-wrap:wrap}.u6-grid{display:grid;gap:10px;margin-top:10px}.u6-card{background:#081321;border-radius:12px;padding:10px}.u6-meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:9px}.u6-metric{background:#06101c;border-radius:10px;padding:9px}.u6-metric b{display:block;font-size:18px;margin-top:2px}.u6-note{font-size:12px;color:#96aac1;line-height:1.4;margin-top:8px}.u6-canvas{width:100%;height:330px;display:block;background:radial-gradient(circle at 50% 30%,#102a43,#02070d 70%);border-radius:12px;touch-action:none}.u6-hud-edit .hud>*{pointer-events:auto!important;touch-action:none;outline:1px dashed rgba(84,199,255,.8);cursor:move}.u6-hud-edit .hud{pointer-events:auto!important}.u6-edit-badge{position:absolute;top:8px;left:50%;transform:translateX(-50%);z-index:30;background:rgba(4,12,20,.85);border:1px solid rgba(84,199,255,.7);border-radius:999px;padding:5px 10px;font-size:11px;color:white;pointer-events:none}.u6-park{font-weight:750}.u6-tag{display:inline-flex;padding:4px 7px;border-radius:999px;background:#0d2135;border:1px solid #29435f;margin:3px 4px 0 0;font-size:11px}@media(min-width:760px){.u6-grid{grid-template-columns:2fr 1fr}.u6-meta{grid-template-columns:repeat(2,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.append(st);
function el(tag,cls,html){const n=document.createElement(tag);if(cls)n.className=cls;if(html!=null)n.innerHTML=html;return n}
function fmt(n,d=1){return Number.isFinite(n)?n.toFixed(d):'–'}
function hav(a,b){const r=Math.PI/180,R=6371000,q=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lon-a.lon)*r/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function buildUI(){const host=document.querySelector('main');if(!host||document.getElementById('u6Panel'))return;const p=el('section','u6-panel');p.id='u6Panel';p.innerHTML=`<div class="u6-head"><div><h2>Streckenrekonstruktion & HUD-Layout</h2><div class="u6-note">GPS-/Höhen-basierte Näherung. Ziehen zum Drehen, Zwei-Finger-Geste oder Mausrad zum Zoomen.</div></div><div class="u6-actions"><button id="u6Edit">HUD verschieben</button><button id="u6ResetHud">HUD zurücksetzen</button><button id="u6Identify">Park identifizieren</button><button id="u6Save">Komplettpaket JSON</button></div></div><div class="u6-grid"><div class="u6-card"><canvas id="u6Route" class="u6-canvas" width="1000" height="620"></canvas></div><div class="u6-card"><div class="label">Erkannter Standort</div><div id="u6Place" class="u6-park">Noch nicht bestimmt</div><div id="u6Tags"></div><div class="u6-meta"><div class="u6-metric"><span class="label">Distanz</span><b id="u6Dist">0 m</b></div><div class="u6-metric"><span class="label">Höhenspanne</span><b id="u6Height">–</b></div><div class="u6-metric"><span class="label">Max. Steigung</span><b id="u6Slope">–</b></div><div class="u6-metric"><span class="label">Kurvenindex</span><b id="u6Curve">–</b></div></div><div class="u6-note" id="u6Info">Die App klassifiziert Starttyp, Steigungen und Kurven aus GPS, Geschwindigkeit, Höhe und Bewegungssensoren. Loopings und Inversionen können im Browser nur als mögliche Ereignisse markiert werden.</div><div class="u6-note">Kartendaten/Geocoding © OpenStreetMap-Mitwirkende.</div></div></div>`;host.append(p);bindUI();restoreHud();drawRoute()}
function bindUI(){document.getElementById('u6Edit').onclick=toggleEdit;document.getElementById('u6ResetHud').onclick=()=>{localStorage.removeItem('ridetracker-hud-layout');location.reload()};document.getElementById('u6Identify').onclick=identifyPark;document.getElementById('u6Save').onclick=saveBundle;const c=document.getElementById('u6Route');c.addEventListener('pointerdown',e=>{U.drag={x:e.clientX,y:e.clientY,rx:U.rotX,rz:U.rotZ};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!U.drag)return;U.rotZ=U.drag.rz+(e.clientX-U.drag.x)*.008;U.rotX=Math.max(-1.4,Math.min(.2,U.drag.rx+(e.clientY-U.drag.y)*.008));drawRoute()});c.addEventListener('pointerup',()=>U.drag=null);c.addEventListener('wheel',e=>{e.preventDefault();U.zoom=Math.max(.45,Math.min(3,U.zoom*(e.deltaY>0?.9:1.1)));drawRoute()},{passive:false})}
function hudParts(){const hud=document.querySelector('.hud');if(!hud)return[];return [...hud.children].filter(n=>!n.classList.contains('u6-edit-badge'))}
function toggleEdit(){U.editing=!U.editing;document.body.classList.toggle('u6-hud-edit',U.editing);document.getElementById('u6Edit').textContent=U.editing?'Layout speichern':'HUD verschieben';const hud=document.querySelector('.hud');if(!hud)return;if(U.editing){const b=el('div','u6-edit-badge','HUD-Elemente mit dem Finger verschieben');hud.append(b);hudParts().forEach(makeDraggable)}else{hud.querySelector('.u6-edit-badge')?.remove();saveHud()}}
function makeDraggable(node){if(node.dataset.u6drag)return;node.dataset.u6drag='1';node.addEventListener('pointerdown',e=>{if(!U.editing)return;e.preventDefault();const hud=node.parentElement,hr=hud.getBoundingClientRect(),r=node.getBoundingClientRect();node.style.left=(r.left-hr.left)+'px';node.style.top=(r.top-hr.top)+'px';node.style.right='auto';node.style.bottom='auto';node.style.position='absolute';const sx=e.clientX,sy=e.clientY,l=parseFloat(node.style.left),t=parseFloat(node.style.top);node.setPointerCapture(e.pointerId);const mv=q=>{node.style.left=Math.max(0,Math.min(hr.width-r.width,l+q.clientX-sx))+'px';node.style.top=Math.max(0,Math.min(hr.height-r.height,t+q.clientY-sy))+'px'};const up=()=>{node.removeEventListener('pointermove',mv);node.removeEventListener('pointerup',up)};node.addEventListener('pointermove',mv);node.addEventListener('pointerup',up)})}
function saveHud(){const hud=document.querySelector('.hud');if(!hud)return;const hr=hud.getBoundingClientRect(),data=hudParts().map((n,i)=>{const r=n.getBoundingClientRect();return{i,x:(r.left-hr.left)/hr.width,y:(r.top-hr.top)/hr.height,w:r.width/hr.width}});localStorage.setItem('ridetracker-hud-layout',JSON.stringify(data))}
function restoreHud(){let data;try{data=JSON.parse(localStorage.getItem('ridetracker-hud-layout'))}catch{}if(!data)return;const hud=document.querySelector('.hud');if(!hud)return;data.forEach(d=>{const n=hud.children[d.i];if(!n)return;n.style.position='absolute';n.style.left=(d.x*100)+'%';n.style.top=(d.y*100)+'%';n.style.right='auto';n.style.bottom='auto';if(d.w)n.style.width=(d.w*100)+'%'})}
const oldWatch=navigator.geolocation?.watchPosition?.bind(navigator.geolocation),oldGet=navigator.geolocation?.getCurrentPosition?.bind(navigator.geolocation);
function capture(pos){const c=pos.coords,p={t:Date.now(),lat:c.latitude,lon:c.longitude,alt:Number.isFinite(c.altitude)?c.altitude:null,acc:c.accuracy,altAcc:c.altitudeAccuracy,speed:c.speed,heading:c.heading};const last=U.route.at(-1);if(!last||hav(last,p)>.4||p.t-last.t>1500)U.route.push(p);if(U.route.length>6000)U.route.shift();updateStats();drawRoute()}
if(oldWatch)navigator.geolocation.watchPosition=(ok,err,opt)=>oldWatch(p=>{capture(p);ok?.(p)},err,opt);if(oldGet)navigator.geolocation.getCurrentPosition=(ok,err,opt)=>oldGet(p=>{capture(p);ok?.(p)},err,opt);
window.addEventListener('devicemotion',e=>{const r=e.rotationRate||{},a=e.accelerationIncludingGravity||{};U.motion.push({t:Date.now(),rot:Math.hypot(r.alpha||0,r.beta||0,r.gamma||0),g:Math.hypot(a.x||0,a.y||0,a.z||0)/9.80665});if(U.motion.length>10000)U.motion.shift()},{passive:true});
function routeAnalysis(){let dist=0,maxSlope=0,turn=0,turnN=0;const p=U.route;for(let i=1;i<p.length;i++){const d=hav(p[i-1],p[i]);if(d<100)dist+=d;if(d>2&&p[i].alt!=null&&p[i-1].alt!=null)maxSlope=Math.max(maxSlope,Math.abs(Math.atan2(p[i].alt-p[i-1].alt,d)*180/Math.PI));if(i>1){const b1=bearing(p[i-2],p[i-1]),b2=bearing(p[i-1],p[i]);let q=Math.abs(b2-b1);if(q>180)q=360-q;if(d>1&&d<50){turn+=q;turnN++}}}const alts=p.map(x=>x.alt).filter(Number.isFinite),span=alts.length?Math.max(...alts)-Math.min(...alts):NaN;let start='Unbekannt';if(p.length>4){for(let i=1;i<p.length;i++){const dt=(p[i].t-p[i-1].t)/1000,ds=((p[i].speed||0)-(p[i-1].speed||0))*3.6;if(dt>0&&dt<6&&ds/dt>5){start='Launch/Abschuss';break}}if(start==='Unbekannt'&&span>8){const slow=p.filter(x=>Number.isFinite(x.speed)&&x.speed*3.6<25).length/p.length;if(slow>.35)start='Lifthill/klassisch'}}const inv=U.motion.filter(x=>x.rot>150&&x.g<1.3).length;return{dist,span,maxSlope,curve:turnN?turn/turnN:0,start,possibleInversions:Math.round(inv/20)}}
function bearing(a,b){const r=Math.PI/180,y=Math.sin((b.lon-a.lon)*r)*Math.cos(b.lat*r),x=Math.cos(a.lat*r)*Math.sin(b.lat*r)-Math.sin(a.lat*r)*Math.cos(b.lat*r)*Math.cos((b.lon-a.lon)*r);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function updateStats(){const a=routeAnalysis();document.getElementById('u6Dist').textContent=a.dist<1000?fmt(a.dist,0)+' m':fmt(a.dist/1000,2)+' km';document.getElementById('u6Height').textContent=fmt(a.span,1)+' m';document.getElementById('u6Slope').textContent=fmt(a.maxSlope,0)+'°';document.getElementById('u6Curve').textContent=fmt(a.curve,0)+'°';document.getElementById('u6Tags').innerHTML=`<span class="u6-tag">${a.start}</span><span class="u6-tag">${a.possibleInversions} mögliche Inversionen</span><span class="u6-tag">${U.route.length} GPS-Punkte</span>`}
function projected(){const p=U.route;if(p.length<2)return[];const lat0=p[0].lat*Math.PI/180,baseAlt=p.find(x=>Number.isFinite(x.alt))?.alt||0;let pts=p.map(q=>({x:(q.lon-p[0].lon)*111320*Math.cos(lat0),y:(q.lat-p[0].lat)*111320,z:(q.alt??baseAlt)-baseAlt}));let minX=Math.min(...pts.map(q=>q.x)),maxX=Math.max(...pts.map(q=>q.x)),minY=Math.min(...pts.map(q=>q.y)),maxY=Math.max(...pts.map(q=>q.y)),minZ=Math.min(...pts.map(q=>q.z)),maxZ=Math.max(...pts.map(q=>q.z));const cx=(minX+maxX)/2,cy=(minY+maxY)/2,cz=(minZ+maxZ)/2,scale=1/Math.max(10,maxX-minX,maxY-minY,(maxZ-minZ)*2);return pts.map(q=>({x:(q.x-cx)*scale,y:(q.y-cy)*scale,z:(q.z-cz)*scale*2}))}
function drawRoute(){const c=document.getElementById('u6Route');if(!c)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='rgba(255,255,255,.08)';for(let i=1;i<10;i++){x.beginPath();x.moveTo(0,i*h/10);x.lineTo(w,i*h/10);x.stroke()}const pts=projected();if(pts.length<2){x.fillStyle='#96aac1';x.font='24px system-ui';x.textAlign='center';x.fillText('GPS-Strecke wird während der Aufnahme aufgebaut',w/2,h/2);return}const cz=Math.cos(U.rotZ),sz=Math.sin(U.rotZ),cx=Math.cos(U.rotX),sx=Math.sin(U.rotX);const q=pts.map(p=>{let X=p.x*cz-p.y*sz,Y=p.x*sz+p.y*cz,Z=p.z;let Y2=Y*cx-Z*sx,Z2=Y*sx+Z*cx;const k=U.zoom*(1.3/(1.8+Y2));return{x:w/2+X*w*.75*k,y:h*.58-Z2*h*.8*k,z:Z2}});for(let i=1;i<q.length;i++){const hue=190+Math.max(-50,Math.min(80,pts[i].z*120));x.strokeStyle=`hsl(${hue} 85% 62%)`;x.lineWidth=5;x.beginPath();x.moveTo(q[i-1].x,q[i-1].y);x.lineTo(q[i].x,q[i].y);x.stroke()}x.fillStyle='#54df9a';x.beginPath();x.arc(q[0].x,q[0].y,8,0,Math.PI*2);x.fill();x.fillStyle='#ff6680';x.beginPath();x.arc(q.at(-1).x,q.at(-1).y,8,0,Math.PI*2);x.fill()}
async function identifyPark(){if(!U.route.length){alert('Noch kein Standort vorhanden.');return}const p=U.route[Math.floor(U.route.length/2)],out=document.getElementById('u6Place');out.textContent='Standort wird bestimmt …';try{const key=`rt-place-${p.lat.toFixed(3)}-${p.lon.toFixed(3)}`,cached=localStorage.getItem(key);let j=cached&&JSON.parse(cached);if(!j){const url=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.lat}&lon=${p.lon}&zoom=18&addressdetails=1&extratags=1&namedetails=1`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('Geocoding '+r.status);j=await r.json();localStorage.setItem(key,JSON.stringify(j))}const a=j.address||{},name=j.namedetails?.name||j.name||a.theme_park||a.attraction||a.leisure||a.tourism;U.place={display_name:j.display_name,address:a,lat:p.lat,lon:p.lon,osm_type:j.osm_type,osm_id:j.osm_id};U.park=name||[a.suburb,a.city||a.town||a.village,a.country].filter(Boolean).join(', ');out.textContent=U.park||j.display_name||'Standort gespeichert';updateStats()}catch(e){out.textContent='Standort gespeichert, Park nicht identifiziert';U.place={lat:p.lat,lon:p.lon,error:e.message}}}
function saveBundle(){const a=routeAnalysis(),data={format:'ridetracker-update6',saved_at:new Date().toISOString(),park:U.park,place:U.place,hud_layout:JSON.parse(localStorage.getItem('ridetracker-hud-layout')||'null'),analysis:a,route:U.route,motion_events:U.motion};const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(b);link.download=`ride-complete-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
const init=()=>{buildUI();const stop=document.getElementById('stop');stop?.addEventListener('click',()=>setTimeout(()=>{updateStats();identifyPark()},800));setInterval(()=>{if(U.route.length)updateStats()},3000)};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();