(() => {
  'use strict';
  const FOCUS_KEY='rideTracker.libraryFocusRideId.v1';
  const db=()=>window.RideTrackerDatabase;
  const engine=()=>window.RideTrackerReferenceEngine;
  const finite=value=>Number.isFinite(Number(value));
  const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,v));
  const radians=deg=>deg*Math.PI/180;
  const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  function distanceMeters(a,b){const R=6371000,dLat=radians(Number(b.latitude)-Number(a.latitude)),dLon=radians(Number(b.longitude)-Number(a.longitude)),lat1=radians(Number(a.latitude)),lat2=radians(Number(b.latitude));const q=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
  function similarity(a,b,tolerance){if(!finite(a)||!finite(b)||Number(b)===0)return null;return clamp(1-Math.abs(Number(a)-Number(b))/Math.max(Math.abs(Number(b))*tolerance,1));}
  function nameSimilarity(a,b){const x=norm(a),y=norm(b);if(!x||!y)return null;if(x===y)return 1;if(x.includes(y)||y.includes(x))return .88;const xs=new Set(x.split(' ')),ys=new Set(y.split(' '));const overlap=[...xs].filter(v=>ys.has(v)).length;return overlap/Math.max(xs.size,ys.size);}
  function packageGps(pkg){const direct=Array.isArray(pkg?.document?.gps?.points)?pkg.document.gps.points:[];if(direct.length)return direct;return(Array.isArray(pkg?.document?.samples)?pkg.document.samples:[]).filter(s=>finite(s.latitude)&&finite(s.longitude));}
  function ownMetrics(pkg){const samples=Array.isArray(pkg?.document?.samples)?pkg.document.samples:[];let maxSpeed=0,maxG=0;for(const s of samples){const speed=finite(s.speedKmh)?Number(s.speedKmh):(finite(s.speedMS)?Number(s.speedMS)*3.6:0);const total=finite(s.totalG)?Math.abs(Number(s.totalG)):Math.hypot(Number(s.normalG??s.normal??0),Number(s.lateralG??s.lateral??0),Number(s.longitudinalG??s.longitudinal??0));maxSpeed=Math.max(maxSpeed,speed);maxG=Math.max(maxG,total);}return{distanceM:Number(pkg?.distanceMeters||0),durationS:Number(pkg?.durationSeconds||0),maxSpeedKmh:maxSpeed,maxG};}
  function tagNumber(tags,names){for(const name of names){const raw=tags?.[name];if(raw==null)continue;const match=String(raw).replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);if(match)return Number(match[0]);}return null;}
  async function referenceFor(attraction){const tags=attraction?.tags||{};let reference={name:attraction?.name,lengthM:tagNumber(tags,['length','track_length']),maxSpeedKmh:tagNumber(tags,['maxspeed','max_speed','speed']),heightM:tagNumber(tags,['height','maxheight']),durationS:tagNumber(tags,['duration']),maxG:tagNumber(tags,['max_g_force','g_force','max_g']),sources:[attraction?.provider||'unknown']};const qid=attraction?.wikidata||tags.wikidata;if(qid&&engine()?.wikidataReference){try{const wd=await engine().wikidataReference(qid);if(wd){reference={...reference,lengthM:reference.lengthM??wd.lengthM,heightM:reference.heightM??wd.heightM,maxSpeedKmh:reference.maxSpeedKmh??wd.maxSpeed,sources:[...new Set([...reference.sources,'wikidata'])],wikidata:wd};}}catch(_){}}return reference;}
  function minTrackDistance(points,target){if(!points.length||!finite(target?.latitude)||!finite(target?.longitude))return null;let best=Infinity;for(const p of points){if(!finite(p.latitude)||!finite(p.longitude))continue;best=Math.min(best,distanceMeters(p,target));}return Number.isFinite(best)?best:null;}
  function confidence(evidence){let score=0,total=0;const used=[];for(const item of evidence){if(item.value==null||!Number.isFinite(item.value))continue;score+=item.weight*clamp(item.value);total+=item.weight;used.push({key:item.key,weight:item.weight,value:clamp(item.value)});}return{score:total?score/total:0,percent:Math.round((total?score/total:0)*100),coverage:total,used};}
  async function scoreCandidate({pkg,park,attraction,parkName,attractionName}){const points=packageGps(pkg),own=ownMetrics(pkg),reference=attraction?await referenceFor(attraction):null;const parkDistance=points.length&&park?minTrackDistance(points,park):null,rideDistance=points.length&&attraction?minTrackDistance(points,attraction):null;const evidence=[
    {key:'gpsPark',weight:.35,value:parkDistance==null?null:clamp(1-parkDistance/2500)},
    {key:'parkName',weight:.15,value:park?nameSimilarity(parkName||park.name,park.name):null},
    {key:'gpsAttraction',weight:.15,value:rideDistance==null?null:clamp(1-rideDistance/500)},
    {key:'speed',weight:.10,value:reference?.maxSpeedKmh?similarity(own.maxSpeedKmh,reference.maxSpeedKmh,.35):null},
    {key:'duration',weight:.10,value:reference?.durationS?similarity(own.durationS,reference.durationS,.4):null},
    {key:'distance',weight:.10,value:reference?.lengthM?similarity(own.distanceM,reference.lengthM,.35):null},
    {key:'community',weight:.05,value:attractionName&&attraction?nameSimilarity(attractionName,attraction.name):attraction?.provider==='themeparks-wiki'?1:null}
  ];const result=confidence(evidence);return{...result,parkDistanceM:parkDistance,attractionDistanceM:rideDistance,reference,own};}
  async function rankAttractions(pkg,park,attractions){const results=[];for(const attraction of attractions||[]){const scored=await scoreCandidate({pkg,park,attraction,parkName:park?.name,attractionName:attraction?.name});results.push({attraction,...scored});}return results.sort((a,b)=>b.score-a.score);}
  async function currentPackage(){const id=sessionStorage.getItem(FOCUS_KEY);if(!id||!db())return null;return db().get(db().stores.ridePackages,id);}
  function ensureScoreHost(panel){let host=panel.querySelector('[data-confidence]');if(!host){host=document.createElement('div');host.dataset.confidence='';host.style.marginTop='10px';host.style.padding='10px';host.style.border='1px solid #29435f';host.style.borderRadius='12px';host.style.background='#07131f';panel.appendChild(host);}return host;}
  async function scoreCurrentSelection(panel){const country=panel.querySelector('[data-country]')?.value,parkSelect=panel.querySelector('[data-park]'),rideSelect=panel.querySelector('[data-attraction]'),host=ensureScoreHost(panel);if(!country||!parkSelect?.value){host.textContent='Confidence: Park oder Attraktion auswählen.';return;}const parks=await engine()?.parksForCountry?.(country)||[],parkName=parkSelect.selectedOptions?.[0]?.textContent||'',park=parks.find(p=>norm(p.name)===norm(parkName));if(!park){host.textContent='Confidence: Parkdaten nicht verfügbar.';return;}const pkg=await currentPackage();if(!pkg){host.textContent='Confidence: RidePackage fehlt.';return;}let attraction=null;if(rideSelect?.value){const attractions=await engine()?.attractionsForPark?.(park,country)||[],rideName=rideSelect.selectedOptions?.[0]?.textContent||'';attraction=attractions.find(a=>norm(a.name)===norm(rideName));}
    const score=await scoreCandidate({pkg,park,attraction,parkName,attractionName:rideSelect?.selectedOptions?.[0]?.textContent});const level=score.percent>=80?'hoch':score.percent>=60?'mittel':'niedrig';host.innerHTML=`<strong>Confidence ${score.percent}% · ${level}</strong><div style="color:#96aac1;font-size:12px;margin-top:4px">${score.parkDistanceM!=null?`Parkabstand ${Math.round(score.parkDistanceM)} m · `:''}${score.attractionDistanceM!=null?`Bahnabstand ${Math.round(score.attractionDistanceM)} m · `:''}${Math.round(score.coverage*100)}% der möglichen Evidenz verfügbar.</div>`;
  }
  function install(){const panel=document.querySelector('#rtReference54');if(!panel||panel.dataset.confidenceReady)return;panel.dataset.confidenceReady='1';ensureScoreHost(panel);panel.addEventListener('change',event=>{if(event.target.matches('[data-country],[data-park],[data-attraction]'))setTimeout(()=>void scoreCurrentSelection(panel),0);});const auto=panel.querySelector('[data-auto]');auto?.addEventListener('click',()=>setTimeout(()=>void scoreCurrentSelection(panel),2200));}
  const observer=new MutationObserver(install);observer.observe(document.body,{childList:true,subtree:true});install();
  window.RideTrackerConfidenceEngine={confidence,scoreCandidate,rankAttractions,ownMetrics,referenceFor};
})();
