(() => {
  'use strict';
  const META_KEY='rideTracker.savedRides.v2';
  const FOCUS_KEY='rideTracker.libraryFocusRideId.v1';
  const WIDGET_KEY='rideTracker.dynamicWidgets.v1';
  const byId=id=>document.getElementById(id);
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const db=()=>window.RideTrackerDatabase;

  const style=document.createElement('style');style.id='rtDataParkWidgets53Style';style.textContent=`
    .rt53-danger{background:#8f1730!important;border-color:#ff6680!important}.rt53-note{color:#96aac1;font-size:12px;line-height:1.45}.rt53-reference{margin-top:10px;border:1px solid #29435f;border-radius:13px;padding:11px;background:#07131f}.rt53-reference-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.rt53-reference-grid div{padding:8px;background:#0b1b29;border-radius:9px}.rt53-reference-grid span{display:block;color:#96aac1;font-size:10px;text-transform:uppercase}.rt53-reference-grid b{display:block;margin-top:3px}.rt53-park-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rt53-park-select{width:100%;margin-top:8px;background:#07111f;color:#fff;border:1px solid #29435f;border-radius:10px;padding:10px}
    #rt53WidgetConfigurator{position:fixed;inset:0;z-index:2147483400;background:rgba(0,0,0,.8);display:grid;place-items:center;padding:16px}#rt53WidgetConfigurator[hidden]{display:none!important}.rt53-widget-card{width:min(560px,100%);background:#091626;border:1px solid #35536f;border-radius:18px;padding:16px;color:#fff}.rt53-widget-card h3{margin:0 0 5px}.rt53-widget-card p{color:#96aac1}.rt53-widget-card label{display:grid;gap:5px;margin-top:10px}.rt53-widget-card input{background:#07111f;color:#fff;border:1px solid #29435f;border-radius:9px;padding:10px}.rt53-widget-metrics{display:grid;gap:7px;margin-top:10px}.rt53-widget-metrics label{display:flex;align-items:center;gap:8px;margin:0}.rt53-widget-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
    #rtDynamicSensorHud{position:absolute;inset:0;z-index:57;pointer-events:none}.rt53-dynamic-widget{position:absolute;right:2%;min-width:120px;max-width:42%;padding:8px 10px;border:1px solid #00e5ff;border-radius:11px;background:rgba(6,20,22,.82);color:#fff}.rt53-dynamic-widget strong{display:block;font-size:10px;letter-spacing:.08em;text-transform:uppercase}.rt53-dynamic-values{display:flex;gap:7px;flex-wrap:wrap;margin-top:4px}.rt53-dynamic-values span{font-size:12px;color:#5fd0ff;font-weight:800}
    @media(max-width:520px){.rt53-reference-grid{grid-template-columns:1fr}.rt53-dynamic-widget{max-width:55%}}
  `;document.head.appendChild(style);

  // ----- Ride library: keep track of selected ride and allow video-only hard deletion. -----
  document.addEventListener('click',event=>{const row=event.target.closest?.('[data-ride-id]');if(row?.dataset.rideId)sessionStorage.setItem(FOCUS_KEY,row.dataset.rideId);},true);
  window.addEventListener('ridetracker:ride-saved',event=>{if(event.detail?.rideId)sessionStorage.setItem(FOCUS_KEY,event.detail.rideId);});

  async function deleteStoredVideo(rideId){
    if(!rideId)return false;
    if(!confirm('Das Video dieser Fahrt endgültig aus RideTracker löschen? Telemetrie, Auswertung und Fahrt bleiben erhalten.'))return false;
    const database=db();if(!database)throw new Error('Datenbank ist nicht bereit.');
    await database.delete(database.stores.videos,rideId);
    const meta=read(META_KEY,[]);const item=meta.find(x=>x.id===rideId);if(item){item.hasVideo=false;item.videoDeletedAt=new Date().toISOString();write(META_KEY,meta);}
    const host=byId('rtLibraryVideoHost');const video=host?.querySelector('video');if(video){const url=video.src;video.pause();video.removeAttribute('src');video.load();if(url?.startsWith('blob:'))URL.revokeObjectURL(url);host.innerHTML='<div class="rt-video-placeholder">Video wurde endgültig aus RideTracker gelöscht.</div>';}
    window.RideTrackerHudReplay?.detach?.();
    window.dispatchEvent(new CustomEvent('ridetracker:ride-video-deleted',{detail:{rideId}}));
    return true;
  }
  function installVideoDelete(){
    const detail=document.querySelector('#rtRideLibrary .rt-ride-detail');if(!detail||detail.querySelector('[data-rt53-delete-video]'))return;
    const videoHost=detail.querySelector('#rtLibraryVideoHost');const actions=videoHost?.parentElement?.querySelector('.rt-detail-actions');if(!actions)return;
    const button=document.createElement('button');button.type='button';button.dataset.rt53DeleteVideo='';button.className='rt53-danger';button.textContent='Video endgültig löschen';button.onclick=async()=>{try{if(await deleteStoredVideo(sessionStorage.getItem(FOCUS_KEY)))button.disabled=true;}catch(error){alert(error?.message||error);}};actions.appendChild(button);
    const note=document.createElement('div');note.className='rt53-note';note.textContent='Löscht den in RideTracker gespeicherten Video-Blob. Bereits separat in Safari/Dateien heruntergeladene Kopien können vom Browser nicht entfernt werden.';actions.after(note);
    installParkComparison(detail);
  }

  // ----- GPS -> park -> attraction -> open reference data -> comparison. -----
  const overpass='https://overpass-api.de/api/interpreter';
  const centerOf=element=>element?.center||((Number.isFinite(element?.lat)&&Number.isFinite(element?.lon))?{lat:element.lat,lon:element.lon}:null);
  const distance=(a,b)=>{const R=6371000,r=Math.PI/180,dLat=(b.lat-a.lat)*r,dLon=(b.lon-a.lon)*r,q=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));};
  const tagNumber=(tags,names)=>{for(const name of names){const raw=tags?.[name];if(raw==null)continue;const m=String(raw).replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);if(m)return Number(m[0]);}return null;};
  async function overpassQuery(query){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${overpass}?data=${encodeURIComponent(query)}`,{signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`OpenStreetMap/Overpass ${response.status}`);return await response.json();}finally{clearTimeout(timer);}}
  async function ridePackage(rideId){const database=db();return database&&rideId?database.get(database.stores.ridePackages,rideId):null;}
  function gpsFromPackage(pkg){const samples=Array.isArray(pkg?.document?.samples)?pkg.document.samples:[];return samples.map(s=>({lat:Number(s.latitude??s.lat),lon:Number(s.longitude??s.lon)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));}
  function ownMetrics(pkg){const samples=Array.isArray(pkg?.document?.samples)?pkg.document.samples:[];let maxSpeed=window.RideTrackerGpsMath?.packageMaxSpeedKmh?.(pkg)||0,maxG=0;for(const s of samples){const speed=Number.isFinite(Number(s.speedKmh))?Number(s.speedKmh):(Number(s.speedMS??s.speed)||0)*3.6;const g=Number.isFinite(Number(s.totalG))?Math.abs(Number(s.totalG)):Math.hypot(Number(s.normalG??s.normal??0),Number(s.lateralG??s.lateral??0),Number(s.longitudinalG??s.longitudinal??0));maxSpeed=Math.max(maxSpeed,speed);maxG=Math.max(maxG,g);}return{distance:Number(pkg?.distanceMeters||0),duration:Number(pkg?.durationSeconds||0),maxSpeed,maxG};}
  async function identifyPark(point){const q=`[out:json][timeout:10];(nwr(around:6000,${point.lat},${point.lon})["leisure"~"theme_park|amusement_park"];nwr(around:6000,${point.lat},${point.lon})["tourism"="theme_park"];);out center tags;`;const data=await overpassQuery(q);const parks=(data.elements||[]).map(e=>({...e,center:centerOf(e)})).filter(e=>e.center&&e.tags?.name).sort((a,b)=>distance(point,a.center)-distance(point,b.center));return parks[0]||null;}
  async function parkAttractions(park){const p=park.center,radius=2500;const q=`[out:json][timeout:12];(nwr(around:${radius},${p.lat},${p.lon})["roller_coaster"];nwr(around:${radius},${p.lat},${p.lon})["attraction"="roller_coaster"];nwr(around:${radius},${p.lat},${p.lon})["tourism"="attraction"];);out center tags;`;const data=await overpassQuery(q);const seen=new Set();return(data.elements||[]).map(e=>({...e,center:centerOf(e)})).filter(e=>{const name=e.tags?.name;if(!name||seen.has(name))return false;seen.add(name);return true;}).sort((a,b)=>(a.tags?.roller_coaster||a.tags?.attraction==='roller_coaster'?-1:0)-(b.tags?.roller_coaster||b.tags?.attraction==='roller_coaster'?-1:0));}
  function closestAttraction(points,attractions){if(!points.length||!attractions.length)return null;let best=null,bestDistance=Infinity;for(const attraction of attractions){if(!attraction.center)continue;for(const p of points){const d=distance(p,attraction.center);if(d<bestDistance){bestDistance=d;best=attraction;}}}return best?{attraction:best,distance:bestDistance}:null;}
  function referenceMetrics(attraction){const t=attraction?.tags||{};return{name:t.name||'Unbekannte Attraktion',length:tagNumber(t,['length','track_length']),maxSpeed:tagNumber(t,['maxspeed','max_speed','speed']),height:tagNumber(t,['height','maxheight']),duration:tagNumber(t,['duration']),maxG:tagNumber(t,['max_g_force','g_force','max_g']),wikidata:t.wikidata||null,wikipedia:t.wikipedia||null,website:t.website||t['contact:website']||null,source:'OpenStreetMap'};}
  function compareText(own,ref){const parts=[];if(ref.length)parts.push(`Strecke: gemessen ${(own.distance/1000).toFixed(2)} km · Referenz ${(ref.length>=1000?ref.length/1000:ref.length).toFixed(ref.length>=1000?2:0)} ${ref.length>=1000?'km':'m'}`);if(ref.maxSpeed)parts.push(`Max. Tempo: gemessen ${own.maxSpeed.toFixed(1)} km/h · Referenz ${ref.maxSpeed.toFixed(1)} km/h`);if(ref.maxG)parts.push(`Max. G: gemessen ${own.maxG.toFixed(2)} g · Referenz ${ref.maxG.toFixed(2)} g`);if(!parts.length)parts.push(`Eigene Messung: ${own.maxSpeed.toFixed(1)} km/h · ${own.maxG.toFixed(2)} g · ${(own.distance/1000).toFixed(2)} km. Für diese Bahn enthält OpenStreetMap keine belastbaren Geschwindigkeits-/G-Referenzwerte.`);return parts.join(' | ');}
  async function detectForRide(rideId,host){
    const pkg=await ridePackage(rideId);if(!pkg)throw new Error('RidePackage nicht gefunden.');const points=gpsFromPackage(pkg);if(!points.length)throw new Error('Keine GPS-Koordinaten in dieser Fahrt vorhanden.');
    const start=points[Math.min(points.length-1,Math.floor(points.length*.05))];host.textContent='Park wird über OpenStreetMap gesucht …';const park=await identifyPark(start);if(!park)throw new Error('In der Umgebung wurde kein Park in OpenStreetMap gefunden.');host.textContent=`${park.tags.name}: Attraktionen werden geladen …`;const attractions=await parkAttractions(park);const nearest=closestAttraction(points,attractions);return{park,attractions,nearest,points,pkg,own:ownMetrics(pkg)};
  }
  function renderParkResult(box,result){const nearest=result.nearest,auto=nearest&&nearest.distance<250?nearest.attraction:null;const selection=auto||null;box.innerHTML=`<strong>Park erkannt: ${result.park.tags.name}</strong><div class="rt53-note">Quelle: OpenStreetMap/Overpass · ${result.attractions.length} Attraktionen im Park gefunden.${auto?` Nächste passende Attraktion: ${auto.tags.name} (${Math.round(nearest.distance)} m).`:' Bahn nicht eindeutig erkannt – bitte auswählen.'}</div><select class="rt53-park-select"><option value="">Bahn auswählen …</option>${result.attractions.map((a,i)=>`<option value="${i}" ${a===selection?'selected':''}>${String(a.tags?.name||'Attraktion').replace(/</g,'&lt;')}</option>`).join('')}</select><div data-rt53-reference></div>`;const select=box.querySelector('select'),refHost=box.querySelector('[data-rt53-reference]');const show=()=>{const a=result.attractions[Number(select.value)];if(!a){refHost.innerHTML='';return;}const ref=referenceMetrics(a);refHost.innerHTML=`<div class="rt53-reference"><strong>${ref.name}</strong><div class="rt53-reference-grid"><div><span>Referenz-Länge</span><b>${ref.length??'–'}${ref.length?' m':''}</b></div><div><span>Referenz Max Tempo</span><b>${ref.maxSpeed??'–'}${ref.maxSpeed?' km/h':''}</b></div><div><span>Referenz Höhe</span><b>${ref.height??'–'}${ref.height?' m':''}</b></div><div><span>Referenz Max G</span><b>${ref.maxG??'–'}${ref.maxG?' g':''}</b></div></div><p class="rt53-note">${compareText(result.own,ref)}</p><p class="rt53-note">Freie Referenzquelle: OpenStreetMap. Wikidata/Wikipedia-ID wird übernommen, falls im OSM-Datensatz vorhanden. Fehlende Geschwindigkeit/G-Werte werden nicht erfunden.</p></div>`;};select.onchange=show;if(selection){select.value=String(result.attractions.indexOf(selection));show();}};
  function installParkComparison(detail){if(detail.querySelector('[data-rt53-park]'))return;const first=detail.querySelector('.rt-detail-card');if(!first)return;const box=document.createElement('section');box.className='rt-detail-card';box.dataset.rt53Park='';box.innerHTML='<strong>Park- und Bahn-Erkennung</strong><div class="rt53-note">GPS → Park-Kandidat → Attraktionen → freie Referenzdaten → Vergleich mit deiner Messung.</div><div class="rt53-park-actions"><button type="button" data-detect>Automatisch erkennen & vergleichen</button></div><div data-result></div>';box.querySelector('[data-detect]').onclick=async event=>{const b=event.currentTarget,resultHost=box.querySelector('[data-result]');b.disabled=true;try{const result=await detectForRide(sessionStorage.getItem(FOCUS_KEY),resultHost);renderParkResult(resultHost,result);}catch(error){resultHost.innerHTML=`<div class="rt53-note">${error?.message||error}</div>`;}finally{b.disabled=false;}};first.after(box);}

  // ----- Dynamic sensor widgets from actually observed plugin metrics. -----
  const telemetryByPlugin=new Map();const latestMetric=new Map();
  function observeTelemetry(event){const d=event.detail||{},plugin=String(d.pluginId||'');if(!plugin)return;const metric=String(d.metric||d.channelId||'value');if(!telemetryByPlugin.has(plugin))telemetryByPlugin.set(plugin,new Set());telemetryByPlugin.get(plugin).add(metric);if(Number.isFinite(Number(d.value)))latestMetric.set(`${plugin}:${metric}`,{value:Number(d.value),unit:d.unit||'',at:performance.now()});renderDynamicHud();}
  window.addEventListener('ridetracker:plugin-telemetry',observeTelemetry);window.addEventListener('ridetracker:routed-telemetry',observeTelemetry);
  const widgetList=()=>read(WIDGET_KEY,[]);const saveWidgets=list=>{write(WIDGET_KEY,list);renderDynamicHud();};
  const relevant=metric=>!/quality|timestamp|raw/i.test(metric);
  function defaultTitle(plugin){return({'ble-heart-rate':'Puls','external-imu':'Externer Bewegungssensor','external-gnss':'Externes GPS'})[plugin]||'Externer Sensor';}
  function ensureWidgetFor(plugin){const metrics=[...(telemetryByPlugin.get(plugin)||[])].filter(relevant);if(!metrics.length)return openWidgetConfigurator(plugin,[]);const list=widgetList();if(list.some(w=>w.pluginId===plugin))return;list.push({id:`dynamic-${plugin}`,pluginId:plugin,title:defaultTitle(plugin),metrics:metrics.slice(0,3),visible:true,createdAt:new Date().toISOString(),automatic:true});saveWidgets(list);window.dispatchEvent(new CustomEvent('ridetracker:dynamic-widget-created',{detail:{pluginId:plugin,metrics}}));}
  function openWidgetConfigurator(plugin,metrics=[...(telemetryByPlugin.get(plugin)||[])]){let modal=byId('rt53WidgetConfigurator');modal?.remove();modal=document.createElement('section');modal.id='rt53WidgetConfigurator';const all=metrics.length?metrics:['heartRateBpm','acceleration','gyroscope','speedKmh','altitude'];modal.innerHTML=`<div class="rt53-widget-card"><h3>Sensor-Widget konfigurieren</h3><p>Für ${defaultTitle(plugin)} konnten ${metrics.length?'folgende Werte erkannt werden':'noch keine eindeutigen Werte automatisch erkannt werden'}. Wähle die relevanten Anzeigen.</p><label>Widget-Titel<input data-title value="${defaultTitle(plugin)}"></label><div class="rt53-widget-metrics">${all.map(m=>`<label><input type="checkbox" data-metric="${m}" ${metrics.includes(m)?'checked':''}> ${m}</label>`).join('')}</div><label>Zusätzlicher Messwert<input data-custom placeholder="z. B. cadenceRpm"></label><div class="rt53-widget-actions"><button data-save>Widget speichern</button><button data-cancel>Abbrechen</button></div></div>`;modal.querySelector('[data-cancel]').onclick=()=>modal.remove();modal.querySelector('[data-save]').onclick=()=>{const selected=[...modal.querySelectorAll('[data-metric]:checked')].map(x=>x.dataset.metric);const custom=modal.querySelector('[data-custom]').value.trim();if(custom)selected.push(custom);if(!selected.length)return alert('Mindestens einen Messwert auswählen.');const list=widgetList().filter(w=>w.pluginId!==plugin);list.push({id:`dynamic-${plugin}`,pluginId:plugin,title:modal.querySelector('[data-title]').value.trim()||defaultTitle(plugin),metrics:[...new Set(selected)].slice(0,4),visible:true,createdAt:new Date().toISOString(),automatic:false});saveWidgets(list);modal.remove();};document.body.appendChild(modal);}
  window.addEventListener('ridetracker:plugin-connection',event=>{const d=event.detail||{};if(d.connection?.status!=='connected'||!d.pluginId)return;setTimeout(()=>ensureWidgetFor(String(d.pluginId)),3500);});
  function recording(){const stop=byId('stop');return Boolean(window.RideTrackerRecordingFullscreen?.isRecording?.())||Boolean(stop&&!stop.disabled);}
  function renderDynamicHud(){const host=byId('videoWrap');if(!host)return;let layer=byId('rtDynamicSensorHud');if(!layer){layer=document.createElement('div');layer.id='rtDynamicSensorHud';host.appendChild(layer);}layer.style.display=recording()?'block':'none';const widgets=widgetList().filter(w=>w.visible!==false);layer.innerHTML=widgets.map((w,i)=>`<div class="rt53-dynamic-widget" style="top:${3+i*15}%"><strong>${w.title}</strong><div class="rt53-dynamic-values">${w.metrics.map(m=>{const x=latestMetric.get(`${w.pluginId}:${m}`);return `<span>${m}: ${x?`${Math.abs(x.value)<100?x.value.toFixed(1):x.value.toFixed(0)} ${x.unit||''}`:'–'}</span>`;}).join('')}</div></div>`).join('');}
  setInterval(renderDynamicHud,300);

  const observer=new MutationObserver(()=>installVideoDelete());observer.observe(document.body,{childList:true,subtree:true});installVideoDelete();
  window.RideTrackerHardDelete={video:deleteStoredVideo};
  window.RideTrackerParkTrackMatcher={identifyPark,parkAttractions,detectForRide,referenceMetrics};
  window.RideTrackerDynamicWidgets={list:widgetList,configure:openWidgetConfigurator,ensureForPlugin:ensureWidgetFor};
})();
