(()=>{'use strict';
const Q={raw:[],filtered:[],distance:0,lastAccepted:null,lastCandidate:null,view:'front',selected:null};
const $=id=>document.getElementById(id),fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'–';
function hav(a,b){const r=Math.PI/180,R=6371000,q=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lon-a.lon)*r/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
const css=`
.rt8-fs{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;z-index:99999!important;margin:0!important;border-radius:0!important;aspect-ratio:auto!important;background:#000!important}.rt8-fs video{object-fit:contain!important}.rt8-fs .hud{display:block!important}.rt8-exit{display:none;position:absolute;right:12px;bottom:12px;z-index:100001;pointer-events:auto!important;background:rgba(5,12,20,.78);color:#fff;border:1px solid rgba(255,255,255,.25);border-radius:999px;padding:9px 12px}.rt8-fs .rt8-exit{display:block}.rt8{margin-top:10px;border:1px solid #29435f;background:linear-gradient(180deg,#11233a,#0c192a);border-radius:16px;padding:12px}.rt8 h2{margin:0;font-size:18px}.rt8-grid{display:grid;gap:10px;margin-top:10px}.rt8-card{background:#081321;border-radius:12px;padding:10px}.rt8-canvas{width:100%;height:360px;display:block;background:linear-gradient(#0c2236 0 63%,#071019 63%);border-radius:12px}.rt8-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.rt8-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:8px}.rt8-metric{background:#06101c;border-radius:10px;padding:9px}.rt8-metric b{display:block;font-size:18px;margin-top:2px}.rt8-note{font-size:12px;color:#96aac1;line-height:1.45;margin-top:7px}.rt8-selected{margin-top:8px;border:1px solid #29435f;border-radius:10px;padding:9px;background:#06101c}.rt8-badge{display:inline-flex;border:1px solid #29435f;border-radius:999px;padding:4px 7px;margin:3px 3px 0 0;font-size:11px}@media(min-width:800px){.rt8-grid{grid-template-columns:2fr 1fr}.rt8-metrics{grid-template-columns:repeat(2,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.append(st);
function capture(pos){const c=pos.coords,p={t:Date.now(),lat:c.latitude,lon:c.longitude,alt:Number.isFinite(c.altitude)?c.altitude:null,acc:Number.isFinite(c.accuracy)?c.accuracy:999,speed:Number.isFinite(c.speed)?Math.max(0,c.speed):null,heading:c.heading};Q.raw.push(p);if(Q.raw.length>8000)Q.raw.shift();if(p.acc>40)return;const last=Q.lastAccepted;if(!last){Q.filtered.push(p);Q.lastAccepted=p;draw();return}const dt=Math.max(.2,(p.t-last.t)/1000),d=hav(last,p),combined=Math.max(3,(last.acc+p.acc)/2),reported=p.speed??last.speed??0,implied=d/dt;const plausibleMax=Math.max(18,reported*2.5+8);if(implied>plausibleMax&&d>combined)return;const moving=reported>=1.2||implied>=1.5;const significance=Math.max(3.5,Math.min(12,combined*.65));if(!moving&&d<significance)return;if(d<2&&dt<2)return;Q.filtered.push(p);Q.distance+=d;Q.lastAccepted=p;if(Q.filtered.length>6000)Q.filtered.shift();draw();updateMetrics()}
const ow=navigator.geolocation?.watchPosition?.bind(navigator.geolocation),og=navigator.geolocation?.getCurrentPosition?.bind(navigator.geolocation);if(ow)navigator.geolocation.watchPosition=(ok,er,o)=>ow(p=>{capture(p);ok?.(p)},er,o);if(og)navigator.geolocation.getCurrentPosition=(ok,er,o)=>og(p=>{capture(p);ok?.(p)},er,o);
function build(){const main=document.querySelector('main');if(!main||$('rt8'))return;const p=document.createElement('section');p.id='rt8';p.className='rt8';p.innerHTML=`<h2>Qualitätsfilter & Streckenprofil</h2><div class="rt8-note">Die Distanz wird nur aus plausiblen, ausreichend genauen Bewegungssegmenten gebildet. Stationärer GPS-Drift wird verworfen.</div><div class="rt8-actions"><button id="rt8Front">Frontalansicht</button><button id="rt8Top">Draufsicht</button><button id="rt8Reset">GPS-Filter zurücksetzen</button></div><div class="rt8-grid"><div class="rt8-card"><canvas id="rt8Canvas" class="rt8-canvas" width="1000" height="620"></canvas></div><div class="rt8-card"><div class="label">Gefilterte Strecke</div><div class="rt8-metrics"><div class="rt8-metric"><span class="label">Distanz</span><b id="rt8Dist">0 m</b></div><div class="rt8-metric"><span class="label">Punkte</span><b id="rt8Pts">0</b></div><div class="rt8-metric"><span class="label">Verworfen</span><b id="rt8Rejected">0</b></div><div class="rt8-metric"><span class="label">Höhenspanne</span><b id="rt8Height">–</b></div></div><div id="rt8Selected" class="rt8-selected">Keine gespeicherte Spur ausgewählt.</div><div class="rt8-note">Bodenebene = niedrigster plausibler Höhenwert. Browserdaten nutzen GPS-Höhe; die native App verwendet künftig den Barometerverlauf.</div><div class="rt8-note"><span class="rt8-badge">BLE vorbereitet</span><span class="rt8-badge">externe IMU</span><span class="rt8-badge">externer GNSS-Empfänger</span></div></div></div>`;main.append(p);$('rt8Front').onclick=()=>{Q.view='front';draw()};$('rt8Top').onclick=()=>{Q.view='top';draw()};$('rt8Reset').onclick=()=>{Q.raw=[];Q.filtered=[];Q.distance=0;Q.lastAccepted=null;updateMetrics();draw()};setupFullscreen();setupDefaults();observeLibrary();draw()}
function setupDefaults(){const cal=$('calMode');if(cal)cal.value='manual'}
function setupFullscreen(){const wrap=$('videoWrap'),btn=$('fullscreen');if(!wrap||!btn)return;const exit=document.createElement('button');exit.className='rt8-exit';exit.textContent='Vollbild schließen';wrap.append(exit);const toggle=()=>{wrap.classList.toggle('rt8-fs');document.body.style.overflow=wrap.classList.contains('rt8-fs')?'hidden':''};btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();toggle()},{capture:true});exit.onclick=toggle}
function project(){const p=Q.filtered;if(p.length<2)return[];const lat0=p[0].lat*Math.PI/180,base=Math.min(...p.map(x=>x.alt).filter(Number.isFinite),0);const pts=p.map(x=>({x:(x.lon-p[0].lon)*111320*Math.cos(lat0),y:(x.lat-p[0].lat)*111320,z:(x.alt??base)-base}));const minX=Math.min(...pts.map(x=>x.x)),maxX=Math.max(...pts.map(x=>x.x)),minY=Math.min(...pts.map(x=>x.y)),maxY=Math.max(...pts.map(x=>x.y)),maxZ=Math.max(1,...pts.map(x=>x.z));return{pts,minX,maxX,minY,maxY,maxZ,base}}
function draw(){const c=$('rt8Canvas');if(!c)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const d=project();x.strokeStyle='rgba(255,255,255,.12)';x.lineWidth=1;const ground=h*.72;for(let i=0;i<=10;i++){const yy=ground+i*(h-ground)/10;x.beginPath();x.moveTo(0,yy);x.lineTo(w,yy);x.stroke()}for(let i=0;i<=12;i++){const xx=i*w/12;x.beginPath();x.moveTo(xx,ground);x.lineTo(w/2+(xx-w/2)*.25,h);x.stroke()}x.strokeStyle='rgba(95,208,255,.4)';x.lineWidth=2;x.beginPath();x.moveTo(0,ground);x.lineTo(w,ground);x.stroke();if(!d){x.fillStyle='#96aac1';x.font='24px system-ui';x.textAlign='center';x.fillText('Gefilterte Strecke wird aufgebaut',w/2,h/2);return}let q;if(Q.view==='top'){const sx=(w*.82)/Math.max(10,d.maxX-d.minX),sy=(h*.62)/Math.max(10,d.maxY-d.minY),s=Math.min(sx,sy);q=d.pts.map(p=>({x:w/2+(p.x-(d.minX+d.maxX)/2)*s,y:h/2-(p.y-(d.minY+d.maxY)/2)*s,z:p.z}))}else{const dx=d.maxX-d.minX,dy=d.maxY-d.minY,useX=dx>=dy,sH=(w*.82)/Math.max(10,useX?dx:dy),sZ=(h*.5)/Math.max(8,d.maxZ);q=d.pts.map(p=>({x:w*.09+((useX?p.x:p.y)-(useX?d.minX:d.minY))*sH,y:ground-p.z*sZ,z:p.z}))}for(let i=1;i<q.length;i++){const v=q[i].z/d.maxZ;x.strokeStyle=`hsl(${205-v*165} 88% 60%)`;x.lineWidth=5;x.beginPath();x.moveTo(q[i-1].x,q[i-1].y);x.lineTo(q[i].x,q[i].y);x.stroke()}x.fillStyle='#5ee0a0';x.beginPath();x.arc(q[0].x,q[0].y,8,0,Math.PI*2);x.fill();x.fillStyle='#ff6680';x.beginPath();x.arc(q.at(-1).x,q.at(-1).y,8,0,Math.PI*2);x.fill()}
function analysis(route){let dist=0,maxSpeed=0;for(let i=1;i<route.length;i++)dist+=hav(route[i-1],route[i]);for(const p of route)maxSpeed=Math.max(maxSpeed,(p.speed||0)*3.6);const alts=route.map(x=>x.alt).filter(Number.isFinite);return{distance:dist,height:alts.length?Math.max(...alts)-Math.min(...alts):null,maxSpeed,points:route.length,duration:route.length?(route.at(-1).t-route[0].t)/1000:0}}
function updateMetrics(){const a=analysis(Q.filtered),alts=Q.filtered.map(x=>x.alt).filter(Number.isFinite);$('rt8Dist').textContent=fmt(Q.distance,0)+' m';$('rt8Pts').textContent=Q.filtered.length;$('rt8Rejected').textContent=Math.max(0,Q.raw.length-Q.filtered.length);$('rt8Height').textContent=alts.length?fmt(Math.max(...alts)-Math.min(...alts),1)+' m':'–'}
function observeLibrary(){const host=$('u7List');if(!host){setTimeout(observeLibrary,500);return}const show=()=>{host.querySelectorAll('[data-show]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>showSelected(b.dataset.show),50)))};new MutationObserver(show).observe(host,{childList:true,subtree:true});show()}
function showSelected(id){let rides=[];try{rides=JSON.parse(localStorage.getItem('ridetracker-library')||'[]')}catch{}const r=rides.find(x=>x.id===id);if(!r)return;Q.selected=r;const a=analysis(r.route||[]);$('rt8Selected').innerHTML=`<b>${String(r.name||'Unbekannte Bahn')}</b><div class="rt8-note">${new Date(r.savedAt).toLocaleString()}</div><div class="rt8-metrics"><div class="rt8-metric"><span class="label">Distanz</span><b>${fmt(a.distance,0)} m</b></div><div class="rt8-metric"><span class="label">Dauer</span><b>${fmt(a.duration,1)} s</b></div><div class="rt8-metric"><span class="label">Max. Tempo</span><b>${fmt(a.maxSpeed,1)} km/h</b></div><div class="rt8-metric"><span class="label">Höhenspanne</span><b>${fmt(a.height,1)} m</b></div></div>`}
(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build):build());
})();